// @generated by protoc-gen-es v2.6.0 with parameter "json_types=true,import_extension=js"
// @generated from file zitadel/filter/v2beta/filter.proto (package zitadel.filter.v2beta, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, tsEnum } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import { file_protoc_gen_openapiv2_options_annotations } from "../../../protoc-gen-openapiv2/options/annotations_pb.js";
import { file_validate_validate } from "../../../validate/validate_pb.js";

/**
 * Describes the file zitadel/filter/v2beta/filter.proto.
 */
export const file_zitadel_filter_v2beta_filter = /*@__PURE__*/
  fileDesc("CiJ6aXRhZGVsL2ZpbHRlci92MmJldGEvZmlsdGVyLnByb3RvEhV6aXRhZGVsLmZpbHRlci52MmJldGEiPwoRUGFnaW5hdGlvblJlcXVlc3QSDgoGb2Zmc2V0GAEgASgEEg0KBWxpbWl0GAIgASgNEgsKA2FzYxgDIAEoCCJZChJQYWdpbmF0aW9uUmVzcG9uc2USIAoMdG90YWxfcmVzdWx0GAEgASgEQgqSQQdKBSIxMDAiEiEKDWFwcGxpZWRfbGltaXQYAiABKARCCpJBB0oFIjEwMCIiOwoISURGaWx0ZXISLwoCaWQYASABKAlCI5JBGEoTIjY5NjI5MDIzOTA2NDg4MzM3InjIAfpCBXIDGMgBIqkBCg9UaW1lc3RhbXBGaWx0ZXISTgoJdGltZXN0YW1wGAEgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcEIfkkEcShoiMjAyNC0xMi0xOFQwNzo1MDo0Ny40OTJaIhJGCgZtZXRob2QYAiABKA4yLC56aXRhZGVsLmZpbHRlci52MmJldGEuVGltZXN0YW1wRmlsdGVyTWV0aG9kQgj6QgWCAQIQASJKCgtJbklEc0ZpbHRlchI7CgNpZHMYASADKAlCLpJBK0opWyI2OTYyOTAyMzkwNjQ4ODMzNCIsIjY5NjIyMzY2MDEyMzU1NjYyIl0qzgIKEFRleHRGaWx0ZXJNZXRob2QSHQoZVEVYVF9GSUxURVJfTUVUSE9EX0VRVUFMUxAAEikKJVRFWFRfRklMVEVSX01FVEhPRF9FUVVBTFNfSUdOT1JFX0NBU0UQARIiCh5URVhUX0ZJTFRFUl9NRVRIT0RfU1RBUlRTX1dJVEgQAhIuCipURVhUX0ZJTFRFUl9NRVRIT0RfU1RBUlRTX1dJVEhfSUdOT1JFX0NBU0UQAxIfChtURVhUX0ZJTFRFUl9NRVRIT0RfQ09OVEFJTlMQBBIrCidURVhUX0ZJTFRFUl9NRVRIT0RfQ09OVEFJTlNfSUdOT1JFX0NBU0UQBRIgChxURVhUX0ZJTFRFUl9NRVRIT0RfRU5EU19XSVRIEAYSLAooVEVYVF9GSUxURVJfTUVUSE9EX0VORFNfV0lUSF9JR05PUkVfQ0FTRRAHKi0KEExpc3RGaWx0ZXJNZXRob2QSGQoVTElTVF9GSUxURVJfTUVUSE9EX0lOEAAq3QEKFVRpbWVzdGFtcEZpbHRlck1ldGhvZBIiCh5USU1FU1RBTVBfRklMVEVSX01FVEhPRF9FUVVBTFMQABIjCh9USU1FU1RBTVBfRklMVEVSX01FVEhPRF9HUkVBVEVSEAESLQopVElNRVNUQU1QX0ZJTFRFUl9NRVRIT0RfR1JFQVRFUl9PUl9FUVVBTFMQAhIgChxUSU1FU1RBTVBfRklMVEVSX01FVEhPRF9MRVNTEAMSKgomVElNRVNUQU1QX0ZJTFRFUl9NRVRIT0RfTEVTU19PUl9FUVVBTFMQBELYAQoZY29tLnppdGFkZWwuZmlsdGVyLnYyYmV0YUILRmlsdGVyUHJvdG9QAVo4Z2l0aHViLmNvbS96aXRhZGVsL3ppdGFkZWwvcGtnL2dycGMvZmlsdGVyL3YyYmV0YTtmaWx0ZXKiAgNaRliqAhVaaXRhZGVsLkZpbHRlci5WMmJldGHKAhVaaXRhZGVsXEZpbHRlclxWMmJldGHiAiFaaXRhZGVsXEZpbHRlclxWMmJldGFcR1BCTWV0YWRhdGHqAhdaaXRhZGVsOjpGaWx0ZXI6OlYyYmV0YWIGcHJvdG8z", [file_google_protobuf_timestamp, file_protoc_gen_openapiv2_options_annotations, file_validate_validate]);

/**
 * Describes the message zitadel.filter.v2beta.PaginationRequest.
 * Use `create(PaginationRequestSchema)` to create a new message.
 */
export const PaginationRequestSchema = /*@__PURE__*/
  messageDesc(file_zitadel_filter_v2beta_filter, 0);

/**
 * Describes the message zitadel.filter.v2beta.PaginationResponse.
 * Use `create(PaginationResponseSchema)` to create a new message.
 */
export const PaginationResponseSchema = /*@__PURE__*/
  messageDesc(file_zitadel_filter_v2beta_filter, 1);

/**
 * Describes the message zitadel.filter.v2beta.IDFilter.
 * Use `create(IDFilterSchema)` to create a new message.
 */
export const IDFilterSchema = /*@__PURE__*/
  messageDesc(file_zitadel_filter_v2beta_filter, 2);

/**
 * Describes the message zitadel.filter.v2beta.TimestampFilter.
 * Use `create(TimestampFilterSchema)` to create a new message.
 */
export const TimestampFilterSchema = /*@__PURE__*/
  messageDesc(file_zitadel_filter_v2beta_filter, 3);

/**
 * Describes the message zitadel.filter.v2beta.InIDsFilter.
 * Use `create(InIDsFilterSchema)` to create a new message.
 */
export const InIDsFilterSchema = /*@__PURE__*/
  messageDesc(file_zitadel_filter_v2beta_filter, 4);

/**
 * Describes the enum zitadel.filter.v2beta.TextFilterMethod.
 */
export const TextFilterMethodSchema = /*@__PURE__*/
  enumDesc(file_zitadel_filter_v2beta_filter, 0);

/**
 * @generated from enum zitadel.filter.v2beta.TextFilterMethod
 */
export const TextFilterMethod = /*@__PURE__*/
  tsEnum(TextFilterMethodSchema);

/**
 * Describes the enum zitadel.filter.v2beta.ListFilterMethod.
 */
export const ListFilterMethodSchema = /*@__PURE__*/
  enumDesc(file_zitadel_filter_v2beta_filter, 1);

/**
 * @generated from enum zitadel.filter.v2beta.ListFilterMethod
 */
export const ListFilterMethod = /*@__PURE__*/
  tsEnum(ListFilterMethodSchema);

/**
 * Describes the enum zitadel.filter.v2beta.TimestampFilterMethod.
 */
export const TimestampFilterMethodSchema = /*@__PURE__*/
  enumDesc(file_zitadel_filter_v2beta_filter, 2);

/**
 * @generated from enum zitadel.filter.v2beta.TimestampFilterMethod
 */
export const TimestampFilterMethod = /*@__PURE__*/
  tsEnum(TimestampFilterMethodSchema);

