// @generated by protoc-gen-es v2.6.0 with parameter "json_types=true,import_extension=js"
// @generated from file zitadel/filter/v2/filter.proto (package zitadel.filter.v2, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, tsEnum } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import { file_protoc_gen_openapiv2_options_annotations } from "../../../protoc-gen-openapiv2/options/annotations_pb.js";
import { file_validate_validate } from "../../../validate/validate_pb.js";

/**
 * Describes the file zitadel/filter/v2/filter.proto.
 */
export const file_zitadel_filter_v2_filter = /*@__PURE__*/
  fileDesc("Ch56aXRhZGVsL2ZpbHRlci92Mi9maWx0ZXIucHJvdG8SEXppdGFkZWwuZmlsdGVyLnYyIlwKEVBhZ2luYXRpb25SZXF1ZXN0EhYKBm9mZnNldBgBIAEoBEIGkkEDSgEwEhYKBWxpbWl0GAIgASgNQgeSQQRKAjEwEhcKA2FzYxgDIAEoCEIKkkEHSgVmYWxzZSJVChJQYWdpbmF0aW9uUmVzcG9uc2USHgoMdG90YWxfcmVzdWx0GAEgASgEQgiSQQVKAzEwMBIfCg1hcHBsaWVkX2xpbWl0GAIgASgEQgiSQQVKAzEwMCI7CghJREZpbHRlchIvCgJpZBgBIAEoCUIjkkEYShMiNjk2MjkwMjM5MDY0ODgzMzcieMgB+kIFcgMYyAEipQEKD1RpbWVzdGFtcEZpbHRlchJOCgl0aW1lc3RhbXAYASABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wQh+SQRxKGiIyMDI0LTEyLTE4VDA3OjUwOjQ3LjQ5MloiEkIKBm1ldGhvZBgCIAEoDjIoLnppdGFkZWwuZmlsdGVyLnYyLlRpbWVzdGFtcEZpbHRlck1ldGhvZEII+kIFggECEAEqzgIKEFRleHRGaWx0ZXJNZXRob2QSHQoZVEVYVF9GSUxURVJfTUVUSE9EX0VRVUFMUxAAEikKJVRFWFRfRklMVEVSX01FVEhPRF9FUVVBTFNfSUdOT1JFX0NBU0UQARIiCh5URVhUX0ZJTFRFUl9NRVRIT0RfU1RBUlRTX1dJVEgQAhIuCipURVhUX0ZJTFRFUl9NRVRIT0RfU1RBUlRTX1dJVEhfSUdOT1JFX0NBU0UQAxIfChtURVhUX0ZJTFRFUl9NRVRIT0RfQ09OVEFJTlMQBBIrCidURVhUX0ZJTFRFUl9NRVRIT0RfQ09OVEFJTlNfSUdOT1JFX0NBU0UQBRIgChxURVhUX0ZJTFRFUl9NRVRIT0RfRU5EU19XSVRIEAYSLAooVEVYVF9GSUxURVJfTUVUSE9EX0VORFNfV0lUSF9JR05PUkVfQ0FTRRAHKi0KEExpc3RGaWx0ZXJNZXRob2QSGQoVTElTVF9GSUxURVJfTUVUSE9EX0lOEAAq3QEKFVRpbWVzdGFtcEZpbHRlck1ldGhvZBIiCh5USU1FU1RBTVBfRklMVEVSX01FVEhPRF9FUVVBTFMQABIhCh1USU1FU1RBTVBfRklMVEVSX01FVEhPRF9BRlRFUhABEisKJ1RJTUVTVEFNUF9GSUxURVJfTUVUSE9EX0FGVEVSX09SX0VRVUFMUxACEiIKHlRJTUVTVEFNUF9GSUxURVJfTUVUSE9EX0JFRk9SRRADEiwKKFRJTUVTVEFNUF9GSUxURVJfTUVUSE9EX0JFRk9SRV9PUl9FUVVBTFMQBELAAQoVY29tLnppdGFkZWwuZmlsdGVyLnYyQgtGaWx0ZXJQcm90b1ABWjRnaXRodWIuY29tL3ppdGFkZWwveml0YWRlbC9wa2cvZ3JwYy9maWx0ZXIvdjI7ZmlsdGVyogIDWkZYqgIRWml0YWRlbC5GaWx0ZXIuVjLKAhFaaXRhZGVsXEZpbHRlclxWMuICHVppdGFkZWxcRmlsdGVyXFYyXEdQQk1ldGFkYXRh6gITWml0YWRlbDo6RmlsdGVyOjpWMmIGcHJvdG8z", [file_google_protobuf_timestamp, file_protoc_gen_openapiv2_options_annotations, file_validate_validate]);

/**
 * Describes the message zitadel.filter.v2.PaginationRequest.
 * Use `create(PaginationRequestSchema)` to create a new message.
 */
export const PaginationRequestSchema = /*@__PURE__*/
  messageDesc(file_zitadel_filter_v2_filter, 0);

/**
 * Describes the message zitadel.filter.v2.PaginationResponse.
 * Use `create(PaginationResponseSchema)` to create a new message.
 */
export const PaginationResponseSchema = /*@__PURE__*/
  messageDesc(file_zitadel_filter_v2_filter, 1);

/**
 * Describes the message zitadel.filter.v2.IDFilter.
 * Use `create(IDFilterSchema)` to create a new message.
 */
export const IDFilterSchema = /*@__PURE__*/
  messageDesc(file_zitadel_filter_v2_filter, 2);

/**
 * Describes the message zitadel.filter.v2.TimestampFilter.
 * Use `create(TimestampFilterSchema)` to create a new message.
 */
export const TimestampFilterSchema = /*@__PURE__*/
  messageDesc(file_zitadel_filter_v2_filter, 3);

/**
 * Describes the enum zitadel.filter.v2.TextFilterMethod.
 */
export const TextFilterMethodSchema = /*@__PURE__*/
  enumDesc(file_zitadel_filter_v2_filter, 0);

/**
 * @generated from enum zitadel.filter.v2.TextFilterMethod
 */
export const TextFilterMethod = /*@__PURE__*/
  tsEnum(TextFilterMethodSchema);

/**
 * Describes the enum zitadel.filter.v2.ListFilterMethod.
 */
export const ListFilterMethodSchema = /*@__PURE__*/
  enumDesc(file_zitadel_filter_v2_filter, 1);

/**
 * @generated from enum zitadel.filter.v2.ListFilterMethod
 */
export const ListFilterMethod = /*@__PURE__*/
  tsEnum(ListFilterMethodSchema);

/**
 * Describes the enum zitadel.filter.v2.TimestampFilterMethod.
 */
export const TimestampFilterMethodSchema = /*@__PURE__*/
  enumDesc(file_zitadel_filter_v2_filter, 2);

/**
 * @generated from enum zitadel.filter.v2.TimestampFilterMethod
 */
export const TimestampFilterMethod = /*@__PURE__*/
  tsEnum(TimestampFilterMethodSchema);

