// @generated by protoc-gen-es v2.6.0 with parameter "json_types=true,import_extension=js"
// @generated from file zitadel/feature/v2beta/feature.proto (package zitadel.feature.v2beta, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, tsEnum } from "@bufbuild/protobuf/codegenv2";
import { file_protoc_gen_openapiv2_options_annotations } from "../../../protoc-gen-openapiv2/options/annotations_pb.js";

/**
 * Describes the file zitadel/feature/v2beta/feature.proto.
 */
export const file_zitadel_feature_v2beta_feature = /*@__PURE__*/
  fileDesc("CiR6aXRhZGVsL2ZlYXR1cmUvdjJiZXRhL2ZlYXR1cmUucHJvdG8SFnppdGFkZWwuZmVhdHVyZS52MmJldGEiiwIKC0ZlYXR1cmVGbGFnEjoKB2VuYWJsZWQYASABKAhCKZJBJjIdV2hldGhlciBhIGZlYXR1cmUgaXMgZW5hYmxlZC5KBWZhbHNlEr8BCgZzb3VyY2UYAiABKA4yHi56aXRhZGVsLmZlYXR1cmUudjJiZXRhLlNvdXJjZUKOAZJBigEyhwFUaGUgc291cmNlIHdoZXJlIHRoZSBzZXR0aW5nIG9mIHRoZSBmZWF0dXJlIHdhcyBkZWZpbmVkLiBUaGUgc291cmNlIG1heSBiZSB0aGUgcmVzb3VyY2UgaXRzZWxmIG9yIGEgcmVzb3VyY2Ugb3duZXIgdGhyb3VnaCBpbmhlcml0YW5jZS4i5QIKHkltcHJvdmVkUGVyZm9ybWFuY2VGZWF0dXJlRmxhZxKAAQoPZXhlY3V0aW9uX3BhdGhzGAEgAygOMisueml0YWRlbC5mZWF0dXJlLnYyYmV0YS5JbXByb3ZlZFBlcmZvcm1hbmNlQjqSQTcyMFdoaWNoIG9mIHRoZSBwZXJmb3JtYW5jZSBpbXByb3ZlbWVudHMgaXMgZW5hYmxlZEoDWzFdEr8BCgZzb3VyY2UYAiABKA4yHi56aXRhZGVsLmZlYXR1cmUudjJiZXRhLlNvdXJjZUKOAZJBigEyhwFUaGUgc291cmNlIHdoZXJlIHRoZSBzZXR0aW5nIG9mIHRoZSBmZWF0dXJlIHdhcyBkZWZpbmVkLiBUaGUgc291cmNlIG1heSBiZSB0aGUgcmVzb3VyY2UgaXRzZWxmIG9yIGEgcmVzb3VyY2Ugb3duZXIgdGhyb3VnaCBpbmhlcml0YW5jZS4qnAEKBlNvdXJjZRIWChJTT1VSQ0VfVU5TUEVDSUZJRUQQABIRCg1TT1VSQ0VfU1lTVEVNEAISEwoPU09VUkNFX0lOU1RBTkNFEAMSFwoTU09VUkNFX09SR0FOSVpBVElPThAEEhIKDlNPVVJDRV9QUk9KRUNUEAUSDgoKU09VUkNFX0FQUBAGEg8KC1NPVVJDRV9VU0VSEAciBAgBEAEq/AEKE0ltcHJvdmVkUGVyZm9ybWFuY2USJAogSU1QUk9WRURfUEVSRk9STUFOQ0VfVU5TUEVDSUZJRUQQABIiCh5JTVBST1ZFRF9QRVJGT1JNQU5DRV9PUkdfQllfSUQQARImCiJJTVBST1ZFRF9QRVJGT1JNQU5DRV9QUk9KRUNUX0dSQU5UEAISIAocSU1QUk9WRURfUEVSRk9STUFOQ0VfUFJPSkVDVBADEiMKH0lNUFJPVkVEX1BFUkZPUk1BTkNFX1VTRVJfR1JBTlQQBBIsCihJTVBST1ZFRF9QRVJGT1JNQU5DRV9PUkdfRE9NQUlOX1ZFUklGSUVEEAVC4AEKGmNvbS56aXRhZGVsLmZlYXR1cmUudjJiZXRhQgxGZWF0dXJlUHJvdG9QAVo6Z2l0aHViLmNvbS96aXRhZGVsL3ppdGFkZWwvcGtnL2dycGMvZmVhdHVyZS92MmJldGE7ZmVhdHVyZaICA1pGWKoCFlppdGFkZWwuRmVhdHVyZS5WMmJldGHKAhZaaXRhZGVsXEZlYXR1cmVcVjJiZXRh4gIiWml0YWRlbFxGZWF0dXJlXFYyYmV0YVxHUEJNZXRhZGF0YeoCGFppdGFkZWw6OkZlYXR1cmU6OlYyYmV0YWIGcHJvdG8z", [file_protoc_gen_openapiv2_options_annotations]);

/**
 * Describes the message zitadel.feature.v2beta.FeatureFlag.
 * Use `create(FeatureFlagSchema)` to create a new message.
 */
export const FeatureFlagSchema = /*@__PURE__*/
  messageDesc(file_zitadel_feature_v2beta_feature, 0);

/**
 * Describes the message zitadel.feature.v2beta.ImprovedPerformanceFeatureFlag.
 * Use `create(ImprovedPerformanceFeatureFlagSchema)` to create a new message.
 */
export const ImprovedPerformanceFeatureFlagSchema = /*@__PURE__*/
  messageDesc(file_zitadel_feature_v2beta_feature, 1);

/**
 * Describes the enum zitadel.feature.v2beta.Source.
 */
export const SourceSchema = /*@__PURE__*/
  enumDesc(file_zitadel_feature_v2beta_feature, 0);

/**
 * @generated from enum zitadel.feature.v2beta.Source
 */
export const Source = /*@__PURE__*/
  tsEnum(SourceSchema);

/**
 * Describes the enum zitadel.feature.v2beta.ImprovedPerformance.
 */
export const ImprovedPerformanceSchema = /*@__PURE__*/
  enumDesc(file_zitadel_feature_v2beta_feature, 1);

/**
 * @generated from enum zitadel.feature.v2beta.ImprovedPerformance
 */
export const ImprovedPerformance = /*@__PURE__*/
  tsEnum(ImprovedPerformanceSchema);

