// @generated by protoc-gen-es v2.6.0 with parameter "json_types=true,import_extension=js"
// @generated from file zitadel/feature/v2beta/system.proto (package zitadel.feature.v2beta, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { FeatureFlag, FeatureFlagJson, ImprovedPerformance, ImprovedPerformanceFeatureFlag, ImprovedPerformanceFeatureFlagJson, ImprovedPerformanceJson } from "./feature_pb.js";
import type { Details, DetailsJson } from "../../object/v2beta/object_pb.js";

/**
 * Describes the file zitadel/feature/v2beta/system.proto.
 */
export declare const file_zitadel_feature_v2beta_system: GenFile;

/**
 * @generated from message zitadel.feature.v2beta.SetSystemFeaturesRequest
 */
export declare type SetSystemFeaturesRequest = Message<"zitadel.feature.v2beta.SetSystemFeaturesRequest"> & {
  /**
   * @generated from field: optional bool login_default_org = 1;
   */
  loginDefaultOrg?: boolean;

  /**
   * @generated from field: optional bool user_schema = 4;
   */
  userSchema?: boolean;

  /**
   * @generated from field: optional bool oidc_token_exchange = 5;
   */
  oidcTokenExchange?: boolean;

  /**
   * @generated from field: repeated zitadel.feature.v2beta.ImprovedPerformance improved_performance = 7;
   */
  improvedPerformance: ImprovedPerformance[];

  /**
   * @generated from field: optional bool oidc_single_v1_session_termination = 8;
   */
  oidcSingleV1SessionTermination?: boolean;
};

/**
 * @generated from message zitadel.feature.v2beta.SetSystemFeaturesRequest
 */
export declare type SetSystemFeaturesRequestJson = {
  /**
   * @generated from field: optional bool login_default_org = 1;
   */
  loginDefaultOrg?: boolean;

  /**
   * @generated from field: optional bool user_schema = 4;
   */
  userSchema?: boolean;

  /**
   * @generated from field: optional bool oidc_token_exchange = 5;
   */
  oidcTokenExchange?: boolean;

  /**
   * @generated from field: repeated zitadel.feature.v2beta.ImprovedPerformance improved_performance = 7;
   */
  improvedPerformance?: ImprovedPerformanceJson[];

  /**
   * @generated from field: optional bool oidc_single_v1_session_termination = 8;
   */
  oidcSingleV1SessionTermination?: boolean;
};

/**
 * Describes the message zitadel.feature.v2beta.SetSystemFeaturesRequest.
 * Use `create(SetSystemFeaturesRequestSchema)` to create a new message.
 */
export declare const SetSystemFeaturesRequestSchema: GenMessage<SetSystemFeaturesRequest, {jsonType: SetSystemFeaturesRequestJson}>;

/**
 * @generated from message zitadel.feature.v2beta.SetSystemFeaturesResponse
 */
export declare type SetSystemFeaturesResponse = Message<"zitadel.feature.v2beta.SetSystemFeaturesResponse"> & {
  /**
   * @generated from field: zitadel.object.v2beta.Details details = 1;
   */
  details?: Details;
};

/**
 * @generated from message zitadel.feature.v2beta.SetSystemFeaturesResponse
 */
export declare type SetSystemFeaturesResponseJson = {
  /**
   * @generated from field: zitadel.object.v2beta.Details details = 1;
   */
  details?: DetailsJson;
};

/**
 * Describes the message zitadel.feature.v2beta.SetSystemFeaturesResponse.
 * Use `create(SetSystemFeaturesResponseSchema)` to create a new message.
 */
export declare const SetSystemFeaturesResponseSchema: GenMessage<SetSystemFeaturesResponse, {jsonType: SetSystemFeaturesResponseJson}>;

/**
 * @generated from message zitadel.feature.v2beta.ResetSystemFeaturesRequest
 */
export declare type ResetSystemFeaturesRequest = Message<"zitadel.feature.v2beta.ResetSystemFeaturesRequest"> & {
};

/**
 * @generated from message zitadel.feature.v2beta.ResetSystemFeaturesRequest
 */
export declare type ResetSystemFeaturesRequestJson = {
};

/**
 * Describes the message zitadel.feature.v2beta.ResetSystemFeaturesRequest.
 * Use `create(ResetSystemFeaturesRequestSchema)` to create a new message.
 */
export declare const ResetSystemFeaturesRequestSchema: GenMessage<ResetSystemFeaturesRequest, {jsonType: ResetSystemFeaturesRequestJson}>;

/**
 * @generated from message zitadel.feature.v2beta.ResetSystemFeaturesResponse
 */
export declare type ResetSystemFeaturesResponse = Message<"zitadel.feature.v2beta.ResetSystemFeaturesResponse"> & {
  /**
   * @generated from field: zitadel.object.v2beta.Details details = 1;
   */
  details?: Details;
};

/**
 * @generated from message zitadel.feature.v2beta.ResetSystemFeaturesResponse
 */
export declare type ResetSystemFeaturesResponseJson = {
  /**
   * @generated from field: zitadel.object.v2beta.Details details = 1;
   */
  details?: DetailsJson;
};

/**
 * Describes the message zitadel.feature.v2beta.ResetSystemFeaturesResponse.
 * Use `create(ResetSystemFeaturesResponseSchema)` to create a new message.
 */
export declare const ResetSystemFeaturesResponseSchema: GenMessage<ResetSystemFeaturesResponse, {jsonType: ResetSystemFeaturesResponseJson}>;

/**
 * @generated from message zitadel.feature.v2beta.GetSystemFeaturesRequest
 */
export declare type GetSystemFeaturesRequest = Message<"zitadel.feature.v2beta.GetSystemFeaturesRequest"> & {
};

/**
 * @generated from message zitadel.feature.v2beta.GetSystemFeaturesRequest
 */
export declare type GetSystemFeaturesRequestJson = {
};

/**
 * Describes the message zitadel.feature.v2beta.GetSystemFeaturesRequest.
 * Use `create(GetSystemFeaturesRequestSchema)` to create a new message.
 */
export declare const GetSystemFeaturesRequestSchema: GenMessage<GetSystemFeaturesRequest, {jsonType: GetSystemFeaturesRequestJson}>;

/**
 * @generated from message zitadel.feature.v2beta.GetSystemFeaturesResponse
 */
export declare type GetSystemFeaturesResponse = Message<"zitadel.feature.v2beta.GetSystemFeaturesResponse"> & {
  /**
   * @generated from field: zitadel.object.v2beta.Details details = 1;
   */
  details?: Details;

  /**
   * @generated from field: zitadel.feature.v2beta.FeatureFlag login_default_org = 2;
   */
  loginDefaultOrg?: FeatureFlag;

  /**
   * @generated from field: zitadel.feature.v2beta.FeatureFlag user_schema = 5;
   */
  userSchema?: FeatureFlag;

  /**
   * @generated from field: zitadel.feature.v2beta.FeatureFlag oidc_token_exchange = 6;
   */
  oidcTokenExchange?: FeatureFlag;

  /**
   * @generated from field: zitadel.feature.v2beta.ImprovedPerformanceFeatureFlag improved_performance = 8;
   */
  improvedPerformance?: ImprovedPerformanceFeatureFlag;

  /**
   * @generated from field: zitadel.feature.v2beta.FeatureFlag oidc_single_v1_session_termination = 9;
   */
  oidcSingleV1SessionTermination?: FeatureFlag;
};

/**
 * @generated from message zitadel.feature.v2beta.GetSystemFeaturesResponse
 */
export declare type GetSystemFeaturesResponseJson = {
  /**
   * @generated from field: zitadel.object.v2beta.Details details = 1;
   */
  details?: DetailsJson;

  /**
   * @generated from field: zitadel.feature.v2beta.FeatureFlag login_default_org = 2;
   */
  loginDefaultOrg?: FeatureFlagJson;

  /**
   * @generated from field: zitadel.feature.v2beta.FeatureFlag user_schema = 5;
   */
  userSchema?: FeatureFlagJson;

  /**
   * @generated from field: zitadel.feature.v2beta.FeatureFlag oidc_token_exchange = 6;
   */
  oidcTokenExchange?: FeatureFlagJson;

  /**
   * @generated from field: zitadel.feature.v2beta.ImprovedPerformanceFeatureFlag improved_performance = 8;
   */
  improvedPerformance?: ImprovedPerformanceFeatureFlagJson;

  /**
   * @generated from field: zitadel.feature.v2beta.FeatureFlag oidc_single_v1_session_termination = 9;
   */
  oidcSingleV1SessionTermination?: FeatureFlagJson;
};

/**
 * Describes the message zitadel.feature.v2beta.GetSystemFeaturesResponse.
 * Use `create(GetSystemFeaturesResponseSchema)` to create a new message.
 */
export declare const GetSystemFeaturesResponseSchema: GenMessage<GetSystemFeaturesResponse, {jsonType: GetSystemFeaturesResponseJson}>;

