// @generated by protoc-gen-es v2.6.0 with parameter "json_types=true,import_extension=js"
// @generated from file zitadel/org/v2/org.proto (package zitadel.org.v2, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, tsEnum } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_field_behavior } from "../../../google/api/field_behavior_pb.js";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import { file_protoc_gen_openapiv2_options_annotations } from "../../../protoc-gen-openapiv2/options/annotations_pb.js";
import { file_validate_validate } from "../../../validate/validate_pb.js";
import { file_zitadel_object_v2_object } from "../../object/v2/object_pb.js";

/**
 * Describes the file zitadel/org/v2/org.proto.
 */
export const file_zitadel_org_v2_org = /*@__PURE__*/
  fileDesc("Chh6aXRhZGVsL29yZy92Mi9vcmcucHJvdG8SDnppdGFkZWwub3JnLnYyIt8BCgxPcmdhbml6YXRpb24SJAoCaWQYASABKAlCGJJBFUoTIjY5NjI5MDIzOTA2NDg4MzM0IhIrCgdkZXRhaWxzGAIgASgLMhoueml0YWRlbC5vYmplY3QudjIuRGV0YWlscxIwCgVzdGF0ZRgDIAEoDjIhLnppdGFkZWwub3JnLnYyLk9yZ2FuaXphdGlvblN0YXRlEhwKBG5hbWUYBCABKAlCDpJBC0oJIlpJVEFERUwiEiwKDnByaW1hcnlfZG9tYWluGAUgASgJQhSSQRFKDyJ6aXRhZGVsLmNsb3VkIiqXAQoRT3JnYW5pemF0aW9uU3RhdGUSIgoeT1JHQU5JWkFUSU9OX1NUQVRFX1VOU1BFQ0lGSUVEEAASHQoZT1JHQU5JWkFUSU9OX1NUQVRFX0FDVElWRRABEh8KG09SR0FOSVpBVElPTl9TVEFURV9JTkFDVElWRRACEh4KGk9SR0FOSVpBVElPTl9TVEFURV9SRU1PVkVEEANCqAEKEmNvbS56aXRhZGVsLm9yZy52MkIIT3JnUHJvdG9QAVouZ2l0aHViLmNvbS96aXRhZGVsL3ppdGFkZWwvcGtnL2dycGMvb3JnL3YyO29yZ6ICA1pPWKoCDlppdGFkZWwuT3JnLlYyygIOWml0YWRlbFxPcmdcVjLiAhpaaXRhZGVsXE9yZ1xWMlxHUEJNZXRhZGF0YeoCEFppdGFkZWw6Ok9yZzo6VjJiBnByb3RvMw", [file_google_api_field_behavior, file_google_protobuf_timestamp, file_protoc_gen_openapiv2_options_annotations, file_validate_validate, file_zitadel_object_v2_object]);

/**
 * Describes the message zitadel.org.v2.Organization.
 * Use `create(OrganizationSchema)` to create a new message.
 */
export const OrganizationSchema = /*@__PURE__*/
  messageDesc(file_zitadel_org_v2_org, 0);

/**
 * Describes the enum zitadel.org.v2.OrganizationState.
 */
export const OrganizationStateSchema = /*@__PURE__*/
  enumDesc(file_zitadel_org_v2_org, 0);

/**
 * @generated from enum zitadel.org.v2.OrganizationState
 */
export const OrganizationState = /*@__PURE__*/
  tsEnum(OrganizationStateSchema);

