// @generated by protoc-gen-es v2.6.0 with parameter "json_types=true,import_extension=js"
// @generated from file zitadel/org/v2/query.proto (package zitadel.org.v2, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, tsEnum } from "@bufbuild/protobuf/codegenv2";
import { file_google_api_annotations } from "../../../google/api/annotations_pb.js";
import { file_google_api_field_behavior } from "../../../google/api/field_behavior_pb.js";
import { file_protoc_gen_openapiv2_options_annotations } from "../../../protoc-gen-openapiv2/options/annotations_pb.js";
import { file_validate_validate } from "../../../validate/validate_pb.js";
import { file_zitadel_org_v2_org } from "./org_pb.js";
import { file_zitadel_object_v2_object } from "../../object/v2/object_pb.js";

/**
 * Describes the file zitadel/org/v2/query.proto.
 */
export const file_zitadel_org_v2_query = /*@__PURE__*/
  fileDesc("Chp6aXRhZGVsL29yZy92Mi9xdWVyeS5wcm90bxIOeml0YWRlbC5vcmcudjIi1AIKC1NlYXJjaFF1ZXJ5EjsKCm5hbWVfcXVlcnkYASABKAsyJS56aXRhZGVsLm9yZy52Mi5Pcmdhbml6YXRpb25OYW1lUXVlcnlIABI/Cgxkb21haW5fcXVlcnkYAiABKAsyJy56aXRhZGVsLm9yZy52Mi5Pcmdhbml6YXRpb25Eb21haW5RdWVyeUgAEj0KC3N0YXRlX3F1ZXJ5GAMgASgLMiYueml0YWRlbC5vcmcudjIuT3JnYW5pemF0aW9uU3RhdGVRdWVyeUgAEjcKCGlkX3F1ZXJ5GAQgASgLMiMueml0YWRlbC5vcmcudjIuT3JnYW5pemF0aW9uSURRdWVyeUgAEkEKDWRlZmF1bHRfcXVlcnkYBSABKAsyKC56aXRhZGVsLm9yZy52Mi5EZWZhdWx0T3JnYW5pemF0aW9uUXVlcnlIAEIMCgVxdWVyeRID+EIBIowBChVPcmdhbml6YXRpb25OYW1lUXVlcnkSNQoEbmFtZRgBIAEoCUInkkEWSg4iZ2lnaS1naXJhZmZlInjIAYABAeJBAQL6QgdyBRABGMgBEjwKBm1ldGhvZBgCIAEoDjIiLnppdGFkZWwub2JqZWN0LnYyLlRleHRRdWVyeU1ldGhvZEII+kIFggECEAEikQEKF09yZ2FuaXphdGlvbkRvbWFpblF1ZXJ5EjgKBmRvbWFpbhgBIAEoCUIokkEXSg8iY2l0YWRlbC5jbG91ZCJ4yAGAAQHiQQEC+kIHcgUQARjIARI8CgZtZXRob2QYAiABKA4yIi56aXRhZGVsLm9iamVjdC52Mi5UZXh0UXVlcnlNZXRob2RCCPpCBYIBAhABIlQKFk9yZ2FuaXphdGlvblN0YXRlUXVlcnkSOgoFc3RhdGUYASABKA4yIS56aXRhZGVsLm9yZy52Mi5Pcmdhbml6YXRpb25TdGF0ZUII+kIFggECEAEiTwoTT3JnYW5pemF0aW9uSURRdWVyeRI4CgJpZBgBIAEoCUIskkEbShMiNjk2MjkwMjM5MDY0ODgzMzQieMgBgAEB4kEBAvpCB3IFEAEYyAEiGgoYRGVmYXVsdE9yZ2FuaXphdGlvblF1ZXJ5KmIKFU9yZ2FuaXphdGlvbkZpZWxkTmFtZRInCiNPUkdBTklaQVRJT05fRklFTERfTkFNRV9VTlNQRUNJRklFRBAAEiAKHE9SR0FOSVpBVElPTl9GSUVMRF9OQU1FX05BTUUQAUKqAQoSY29tLnppdGFkZWwub3JnLnYyQgpRdWVyeVByb3RvUAFaLmdpdGh1Yi5jb20veml0YWRlbC96aXRhZGVsL3BrZy9ncnBjL29yZy92MjtvcmeiAgNaT1iqAg5aaXRhZGVsLk9yZy5WMsoCDlppdGFkZWxcT3JnXFYy4gIaWml0YWRlbFxPcmdcVjJcR1BCTWV0YWRhdGHqAhBaaXRhZGVsOjpPcmc6OlYyYgZwcm90bzM", [file_google_api_annotations, file_google_api_field_behavior, file_protoc_gen_openapiv2_options_annotations, file_validate_validate, file_zitadel_org_v2_org, file_zitadel_object_v2_object]);

/**
 * Describes the message zitadel.org.v2.SearchQuery.
 * Use `create(SearchQuerySchema)` to create a new message.
 */
export const SearchQuerySchema = /*@__PURE__*/
  messageDesc(file_zitadel_org_v2_query, 0);

/**
 * Describes the message zitadel.org.v2.OrganizationNameQuery.
 * Use `create(OrganizationNameQuerySchema)` to create a new message.
 */
export const OrganizationNameQuerySchema = /*@__PURE__*/
  messageDesc(file_zitadel_org_v2_query, 1);

/**
 * Describes the message zitadel.org.v2.OrganizationDomainQuery.
 * Use `create(OrganizationDomainQuerySchema)` to create a new message.
 */
export const OrganizationDomainQuerySchema = /*@__PURE__*/
  messageDesc(file_zitadel_org_v2_query, 2);

/**
 * Describes the message zitadel.org.v2.OrganizationStateQuery.
 * Use `create(OrganizationStateQuerySchema)` to create a new message.
 */
export const OrganizationStateQuerySchema = /*@__PURE__*/
  messageDesc(file_zitadel_org_v2_query, 3);

/**
 * Describes the message zitadel.org.v2.OrganizationIDQuery.
 * Use `create(OrganizationIDQuerySchema)` to create a new message.
 */
export const OrganizationIDQuerySchema = /*@__PURE__*/
  messageDesc(file_zitadel_org_v2_query, 4);

/**
 * Describes the message zitadel.org.v2.DefaultOrganizationQuery.
 * Use `create(DefaultOrganizationQuerySchema)` to create a new message.
 */
export const DefaultOrganizationQuerySchema = /*@__PURE__*/
  messageDesc(file_zitadel_org_v2_query, 5);

/**
 * Describes the enum zitadel.org.v2.OrganizationFieldName.
 */
export const OrganizationFieldNameSchema = /*@__PURE__*/
  enumDesc(file_zitadel_org_v2_query, 0);

/**
 * @generated from enum zitadel.org.v2.OrganizationFieldName
 */
export const OrganizationFieldName = /*@__PURE__*/
  tsEnum(OrganizationFieldNameSchema);

