// @generated by protoc-gen-es v2.6.0 with parameter "json_types=true,import_extension=js"
// @generated from file zitadel/oidc/v2beta/oidc_service.proto (package zitadel.oidc.v2beta, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { AuthorizationError, AuthorizationErrorJson, AuthRequest, AuthRequestJson } from "./authorization_pb.js";
import type { Details, DetailsJson } from "../../object/v2beta/object_pb.js";

/**
 * Describes the file zitadel/oidc/v2beta/oidc_service.proto.
 */
export declare const file_zitadel_oidc_v2beta_oidc_service: GenFile;

/**
 * @generated from message zitadel.oidc.v2beta.GetAuthRequestRequest
 */
export declare type GetAuthRequestRequest = Message<"zitadel.oidc.v2beta.GetAuthRequestRequest"> & {
  /**
   * @generated from field: string auth_request_id = 1;
   */
  authRequestId: string;
};

/**
 * @generated from message zitadel.oidc.v2beta.GetAuthRequestRequest
 */
export declare type GetAuthRequestRequestJson = {
  /**
   * @generated from field: string auth_request_id = 1;
   */
  authRequestId?: string;
};

/**
 * Describes the message zitadel.oidc.v2beta.GetAuthRequestRequest.
 * Use `create(GetAuthRequestRequestSchema)` to create a new message.
 */
export declare const GetAuthRequestRequestSchema: GenMessage<GetAuthRequestRequest, {jsonType: GetAuthRequestRequestJson}>;

/**
 * @generated from message zitadel.oidc.v2beta.GetAuthRequestResponse
 */
export declare type GetAuthRequestResponse = Message<"zitadel.oidc.v2beta.GetAuthRequestResponse"> & {
  /**
   * @generated from field: zitadel.oidc.v2beta.AuthRequest auth_request = 1;
   */
  authRequest?: AuthRequest;
};

/**
 * @generated from message zitadel.oidc.v2beta.GetAuthRequestResponse
 */
export declare type GetAuthRequestResponseJson = {
  /**
   * @generated from field: zitadel.oidc.v2beta.AuthRequest auth_request = 1;
   */
  authRequest?: AuthRequestJson;
};

/**
 * Describes the message zitadel.oidc.v2beta.GetAuthRequestResponse.
 * Use `create(GetAuthRequestResponseSchema)` to create a new message.
 */
export declare const GetAuthRequestResponseSchema: GenMessage<GetAuthRequestResponse, {jsonType: GetAuthRequestResponseJson}>;

/**
 * @generated from message zitadel.oidc.v2beta.CreateCallbackRequest
 */
export declare type CreateCallbackRequest = Message<"zitadel.oidc.v2beta.CreateCallbackRequest"> & {
  /**
   * @generated from field: string auth_request_id = 1;
   */
  authRequestId: string;

  /**
   * @generated from oneof zitadel.oidc.v2beta.CreateCallbackRequest.callback_kind
   */
  callbackKind: {
    /**
     * @generated from field: zitadel.oidc.v2beta.Session session = 2;
     */
    value: Session;
    case: "session";
  } | {
    /**
     * @generated from field: zitadel.oidc.v2beta.AuthorizationError error = 3;
     */
    value: AuthorizationError;
    case: "error";
  } | { case: undefined; value?: undefined };
};

/**
 * @generated from message zitadel.oidc.v2beta.CreateCallbackRequest
 */
export declare type CreateCallbackRequestJson = {
  /**
   * @generated from field: string auth_request_id = 1;
   */
  authRequestId?: string;

  /**
   * @generated from field: zitadel.oidc.v2beta.Session session = 2;
   */
  session?: SessionJson;

  /**
   * @generated from field: zitadel.oidc.v2beta.AuthorizationError error = 3;
   */
  error?: AuthorizationErrorJson;
};

/**
 * Describes the message zitadel.oidc.v2beta.CreateCallbackRequest.
 * Use `create(CreateCallbackRequestSchema)` to create a new message.
 */
export declare const CreateCallbackRequestSchema: GenMessage<CreateCallbackRequest, {jsonType: CreateCallbackRequestJson}>;

/**
 * @generated from message zitadel.oidc.v2beta.Session
 */
export declare type Session = Message<"zitadel.oidc.v2beta.Session"> & {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId: string;

  /**
   * @generated from field: string session_token = 2;
   */
  sessionToken: string;
};

/**
 * @generated from message zitadel.oidc.v2beta.Session
 */
export declare type SessionJson = {
  /**
   * @generated from field: string session_id = 1;
   */
  sessionId?: string;

  /**
   * @generated from field: string session_token = 2;
   */
  sessionToken?: string;
};

/**
 * Describes the message zitadel.oidc.v2beta.Session.
 * Use `create(SessionSchema)` to create a new message.
 */
export declare const SessionSchema: GenMessage<Session, {jsonType: SessionJson}>;

/**
 * @generated from message zitadel.oidc.v2beta.CreateCallbackResponse
 */
export declare type CreateCallbackResponse = Message<"zitadel.oidc.v2beta.CreateCallbackResponse"> & {
  /**
   * @generated from field: zitadel.object.v2beta.Details details = 1;
   */
  details?: Details;

  /**
   * @generated from field: string callback_url = 2;
   */
  callbackUrl: string;
};

/**
 * @generated from message zitadel.oidc.v2beta.CreateCallbackResponse
 */
export declare type CreateCallbackResponseJson = {
  /**
   * @generated from field: zitadel.object.v2beta.Details details = 1;
   */
  details?: DetailsJson;

  /**
   * @generated from field: string callback_url = 2;
   */
  callbackUrl?: string;
};

/**
 * Describes the message zitadel.oidc.v2beta.CreateCallbackResponse.
 * Use `create(CreateCallbackResponseSchema)` to create a new message.
 */
export declare const CreateCallbackResponseSchema: GenMessage<CreateCallbackResponse, {jsonType: CreateCallbackResponseJson}>;

/**
 * @generated from service zitadel.oidc.v2beta.OIDCService
 */
export declare const OIDCService: GenService<{
  /**
   * @generated from rpc zitadel.oidc.v2beta.OIDCService.GetAuthRequest
   */
  getAuthRequest: {
    methodKind: "unary";
    input: typeof GetAuthRequestRequestSchema;
    output: typeof GetAuthRequestResponseSchema;
  },
  /**
   * @generated from rpc zitadel.oidc.v2beta.OIDCService.CreateCallback
   */
  createCallback: {
    methodKind: "unary";
    input: typeof CreateCallbackRequestSchema;
    output: typeof CreateCallbackResponseSchema;
  },
}>;

