// @generated by protoc-gen-es v2.6.0 with parameter "json_types=true,import_extension=js"
// @generated from file zitadel/app/v2beta/app.proto (package zitadel.app.v2beta, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Timestamp, TimestampJson } from "@bufbuild/protobuf/wkt";
import type { OIDCConfig, OIDCConfigJson } from "./oidc_pb.js";
import type { APIConfig, APIConfigJson } from "./api_pb.js";
import type { SAMLConfig, SAMLConfigJson } from "./saml_pb.js";
import type { TextFilterMethod, TextFilterMethodJson } from "../../filter/v2/filter_pb.js";

/**
 * Describes the file zitadel/app/v2beta/app.proto.
 */
export declare const file_zitadel_app_v2beta_app: GenFile;

/**
 * @generated from message zitadel.app.v2beta.Application
 */
export declare type Application = Message<"zitadel.app.v2beta.Application"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * The timestamp of the app creation.
   *
   * @generated from field: google.protobuf.Timestamp creation_date = 2;
   */
  creationDate?: Timestamp;

  /**
   * The timestamp of the app update.
   *
   * @generated from field: google.protobuf.Timestamp change_date = 3;
   */
  changeDate?: Timestamp;

  /**
   * @generated from field: zitadel.app.v2beta.AppState state = 4;
   */
  state: AppState;

  /**
   * @generated from field: string name = 5;
   */
  name: string;

  /**
   * @generated from oneof zitadel.app.v2beta.Application.config
   */
  config: {
    /**
     * @generated from field: zitadel.app.v2beta.OIDCConfig oidc_config = 6;
     */
    value: OIDCConfig;
    case: "oidcConfig";
  } | {
    /**
     * @generated from field: zitadel.app.v2beta.APIConfig api_config = 7;
     */
    value: APIConfig;
    case: "apiConfig";
  } | {
    /**
     * @generated from field: zitadel.app.v2beta.SAMLConfig saml_config = 8;
     */
    value: SAMLConfig;
    case: "samlConfig";
  } | { case: undefined; value?: undefined };
};

/**
 * @generated from message zitadel.app.v2beta.Application
 */
export declare type ApplicationJson = {
  /**
   * @generated from field: string id = 1;
   */
  id?: string;

  /**
   * The timestamp of the app creation.
   *
   * @generated from field: google.protobuf.Timestamp creation_date = 2;
   */
  creationDate?: TimestampJson;

  /**
   * The timestamp of the app update.
   *
   * @generated from field: google.protobuf.Timestamp change_date = 3;
   */
  changeDate?: TimestampJson;

  /**
   * @generated from field: zitadel.app.v2beta.AppState state = 4;
   */
  state?: AppStateJson;

  /**
   * @generated from field: string name = 5;
   */
  name?: string;

  /**
   * @generated from field: zitadel.app.v2beta.OIDCConfig oidc_config = 6;
   */
  oidcConfig?: OIDCConfigJson;

  /**
   * @generated from field: zitadel.app.v2beta.APIConfig api_config = 7;
   */
  apiConfig?: APIConfigJson;

  /**
   * @generated from field: zitadel.app.v2beta.SAMLConfig saml_config = 8;
   */
  samlConfig?: SAMLConfigJson;
};

/**
 * Describes the message zitadel.app.v2beta.Application.
 * Use `create(ApplicationSchema)` to create a new message.
 */
export declare const ApplicationSchema: GenMessage<Application, {jsonType: ApplicationJson}>;

/**
 * @generated from message zitadel.app.v2beta.ApplicationSearchFilter
 */
export declare type ApplicationSearchFilter = Message<"zitadel.app.v2beta.ApplicationSearchFilter"> & {
  /**
   * @generated from oneof zitadel.app.v2beta.ApplicationSearchFilter.filter
   */
  filter: {
    /**
     * @generated from field: zitadel.app.v2beta.ApplicationNameQuery name_filter = 1;
     */
    value: ApplicationNameQuery;
    case: "nameFilter";
  } | {
    /**
     * @generated from field: zitadel.app.v2beta.AppState state_filter = 2;
     */
    value: AppState;
    case: "stateFilter";
  } | {
    /**
     * @generated from field: bool api_app_only = 3;
     */
    value: boolean;
    case: "apiAppOnly";
  } | {
    /**
     * @generated from field: bool oidc_app_only = 4;
     */
    value: boolean;
    case: "oidcAppOnly";
  } | {
    /**
     * @generated from field: bool saml_app_only = 5;
     */
    value: boolean;
    case: "samlAppOnly";
  } | { case: undefined; value?: undefined };
};

/**
 * @generated from message zitadel.app.v2beta.ApplicationSearchFilter
 */
export declare type ApplicationSearchFilterJson = {
  /**
   * @generated from field: zitadel.app.v2beta.ApplicationNameQuery name_filter = 1;
   */
  nameFilter?: ApplicationNameQueryJson;

  /**
   * @generated from field: zitadel.app.v2beta.AppState state_filter = 2;
   */
  stateFilter?: AppStateJson;

  /**
   * @generated from field: bool api_app_only = 3;
   */
  apiAppOnly?: boolean;

  /**
   * @generated from field: bool oidc_app_only = 4;
   */
  oidcAppOnly?: boolean;

  /**
   * @generated from field: bool saml_app_only = 5;
   */
  samlAppOnly?: boolean;
};

/**
 * Describes the message zitadel.app.v2beta.ApplicationSearchFilter.
 * Use `create(ApplicationSearchFilterSchema)` to create a new message.
 */
export declare const ApplicationSearchFilterSchema: GenMessage<ApplicationSearchFilter, {jsonType: ApplicationSearchFilterJson}>;

/**
 * @generated from message zitadel.app.v2beta.ApplicationNameQuery
 */
export declare type ApplicationNameQuery = Message<"zitadel.app.v2beta.ApplicationNameQuery"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: zitadel.filter.v2.TextFilterMethod method = 2;
   */
  method: TextFilterMethod;
};

/**
 * @generated from message zitadel.app.v2beta.ApplicationNameQuery
 */
export declare type ApplicationNameQueryJson = {
  /**
   * @generated from field: string name = 1;
   */
  name?: string;

  /**
   * @generated from field: zitadel.filter.v2.TextFilterMethod method = 2;
   */
  method?: TextFilterMethodJson;
};

/**
 * Describes the message zitadel.app.v2beta.ApplicationNameQuery.
 * Use `create(ApplicationNameQuerySchema)` to create a new message.
 */
export declare const ApplicationNameQuerySchema: GenMessage<ApplicationNameQuery, {jsonType: ApplicationNameQueryJson}>;

/**
 * @generated from enum zitadel.app.v2beta.AppState
 */
export enum AppState {
  /**
   * @generated from enum value: APP_STATE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: APP_STATE_ACTIVE = 1;
   */
  ACTIVE = 1,

  /**
   * @generated from enum value: APP_STATE_INACTIVE = 2;
   */
  INACTIVE = 2,

  /**
   * @generated from enum value: APP_STATE_REMOVED = 3;
   */
  REMOVED = 3,
}

/**
 * @generated from enum zitadel.app.v2beta.AppState
 */
export declare type AppStateJson = "APP_STATE_UNSPECIFIED" | "APP_STATE_ACTIVE" | "APP_STATE_INACTIVE" | "APP_STATE_REMOVED";

/**
 * Describes the enum zitadel.app.v2beta.AppState.
 */
export declare const AppStateSchema: GenEnum<AppState, AppStateJson>;

/**
 * @generated from enum zitadel.app.v2beta.AppSorting
 */
export enum AppSorting {
  /**
   * @generated from enum value: APP_SORT_BY_ID = 0;
   */
  APP_SORT_BY_ID = 0,

  /**
   * @generated from enum value: APP_SORT_BY_NAME = 1;
   */
  APP_SORT_BY_NAME = 1,

  /**
   * @generated from enum value: APP_SORT_BY_STATE = 2;
   */
  APP_SORT_BY_STATE = 2,

  /**
   * @generated from enum value: APP_SORT_BY_CREATION_DATE = 3;
   */
  APP_SORT_BY_CREATION_DATE = 3,

  /**
   * @generated from enum value: APP_SORT_BY_CHANGE_DATE = 4;
   */
  APP_SORT_BY_CHANGE_DATE = 4,
}

/**
 * @generated from enum zitadel.app.v2beta.AppSorting
 */
export declare type AppSortingJson = "APP_SORT_BY_ID" | "APP_SORT_BY_NAME" | "APP_SORT_BY_STATE" | "APP_SORT_BY_CREATION_DATE" | "APP_SORT_BY_CHANGE_DATE";

/**
 * Describes the enum zitadel.app.v2beta.AppSorting.
 */
export declare const AppSortingSchema: GenEnum<AppSorting, AppSortingJson>;

