// @generated by protoc-gen-es v2.6.0 with parameter "json_types=true,import_extension=js"
// @generated from file zitadel/app/v2beta/app_service.proto (package zitadel.app.v2beta, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Duration, DurationJson, Timestamp, TimestampJson } from "@bufbuild/protobuf/wkt";
import type { OIDCAppType, OIDCAppTypeJson, OIDCAuthMethodType, OIDCAuthMethodTypeJson, OIDCGrantType, OIDCGrantTypeJson, OIDCLocalizedMessage, OIDCLocalizedMessageJson, OIDCResponseType, OIDCResponseTypeJson, OIDCTokenType, OIDCTokenTypeJson, OIDCVersion, OIDCVersionJson } from "./oidc_pb.js";
import type { LoginVersion, LoginVersionJson } from "./login_pb.js";
import type { APIAuthMethodType, APIAuthMethodTypeJson } from "./api_pb.js";
import type { Application, ApplicationJson, ApplicationSearchFilter, ApplicationSearchFilterJson, AppSorting, AppSortingJson } from "./app_pb.js";
import type { PaginationRequest, PaginationRequestJson, PaginationResponse, PaginationResponseJson } from "../../filter/v2/filter_pb.js";

/**
 * Describes the file zitadel/app/v2beta/app_service.proto.
 */
export declare const file_zitadel_app_v2beta_app_service: GenFile;

/**
 * @generated from message zitadel.app.v2beta.CreateApplicationRequest
 */
export declare type CreateApplicationRequest = Message<"zitadel.app.v2beta.CreateApplicationRequest"> & {
  /**
   * @generated from field: string project_id = 1;
   */
  projectId: string;

  /**
   * @generated from field: string id = 2;
   */
  id: string;

  /**
   * @generated from field: string name = 3;
   */
  name: string;

  /**
   * @generated from oneof zitadel.app.v2beta.CreateApplicationRequest.creation_request_type
   */
  creationRequestType: {
    /**
     * @generated from field: zitadel.app.v2beta.CreateOIDCApplicationRequest oidc_request = 4;
     */
    value: CreateOIDCApplicationRequest;
    case: "oidcRequest";
  } | {
    /**
     * @generated from field: zitadel.app.v2beta.CreateSAMLApplicationRequest saml_request = 5;
     */
    value: CreateSAMLApplicationRequest;
    case: "samlRequest";
  } | {
    /**
     * @generated from field: zitadel.app.v2beta.CreateAPIApplicationRequest api_request = 6;
     */
    value: CreateAPIApplicationRequest;
    case: "apiRequest";
  } | { case: undefined; value?: undefined };
};

/**
 * @generated from message zitadel.app.v2beta.CreateApplicationRequest
 */
export declare type CreateApplicationRequestJson = {
  /**
   * @generated from field: string project_id = 1;
   */
  projectId?: string;

  /**
   * @generated from field: string id = 2;
   */
  id?: string;

  /**
   * @generated from field: string name = 3;
   */
  name?: string;

  /**
   * @generated from field: zitadel.app.v2beta.CreateOIDCApplicationRequest oidc_request = 4;
   */
  oidcRequest?: CreateOIDCApplicationRequestJson;

  /**
   * @generated from field: zitadel.app.v2beta.CreateSAMLApplicationRequest saml_request = 5;
   */
  samlRequest?: CreateSAMLApplicationRequestJson;

  /**
   * @generated from field: zitadel.app.v2beta.CreateAPIApplicationRequest api_request = 6;
   */
  apiRequest?: CreateAPIApplicationRequestJson;
};

/**
 * Describes the message zitadel.app.v2beta.CreateApplicationRequest.
 * Use `create(CreateApplicationRequestSchema)` to create a new message.
 */
export declare const CreateApplicationRequestSchema: GenMessage<CreateApplicationRequest, {jsonType: CreateApplicationRequestJson}>;

/**
 * @generated from message zitadel.app.v2beta.CreateApplicationResponse
 */
export declare type CreateApplicationResponse = Message<"zitadel.app.v2beta.CreateApplicationResponse"> & {
  /**
   * @generated from field: string app_id = 1;
   */
  appId: string;

  /**
   * The timestamp of the app creation.
   *
   * @generated from field: google.protobuf.Timestamp creation_date = 2;
   */
  creationDate?: Timestamp;

  /**
   * @generated from oneof zitadel.app.v2beta.CreateApplicationResponse.creation_response_type
   */
  creationResponseType: {
    /**
     * @generated from field: zitadel.app.v2beta.CreateOIDCApplicationResponse oidc_response = 3;
     */
    value: CreateOIDCApplicationResponse;
    case: "oidcResponse";
  } | {
    /**
     * @generated from field: zitadel.app.v2beta.CreateSAMLApplicationResponse saml_response = 4;
     */
    value: CreateSAMLApplicationResponse;
    case: "samlResponse";
  } | {
    /**
     * @generated from field: zitadel.app.v2beta.CreateAPIApplicationResponse api_response = 5;
     */
    value: CreateAPIApplicationResponse;
    case: "apiResponse";
  } | { case: undefined; value?: undefined };
};

/**
 * @generated from message zitadel.app.v2beta.CreateApplicationResponse
 */
export declare type CreateApplicationResponseJson = {
  /**
   * @generated from field: string app_id = 1;
   */
  appId?: string;

  /**
   * The timestamp of the app creation.
   *
   * @generated from field: google.protobuf.Timestamp creation_date = 2;
   */
  creationDate?: TimestampJson;

  /**
   * @generated from field: zitadel.app.v2beta.CreateOIDCApplicationResponse oidc_response = 3;
   */
  oidcResponse?: CreateOIDCApplicationResponseJson;

  /**
   * @generated from field: zitadel.app.v2beta.CreateSAMLApplicationResponse saml_response = 4;
   */
  samlResponse?: CreateSAMLApplicationResponseJson;

  /**
   * @generated from field: zitadel.app.v2beta.CreateAPIApplicationResponse api_response = 5;
   */
  apiResponse?: CreateAPIApplicationResponseJson;
};

/**
 * Describes the message zitadel.app.v2beta.CreateApplicationResponse.
 * Use `create(CreateApplicationResponseSchema)` to create a new message.
 */
export declare const CreateApplicationResponseSchema: GenMessage<CreateApplicationResponse, {jsonType: CreateApplicationResponseJson}>;

/**
 * @generated from message zitadel.app.v2beta.CreateOIDCApplicationRequest
 */
export declare type CreateOIDCApplicationRequest = Message<"zitadel.app.v2beta.CreateOIDCApplicationRequest"> & {
  /**
   * Callback URI of the authorization request where the code or tokens will be sent to
   *
   * @generated from field: repeated string redirect_uris = 1;
   */
  redirectUris: string[];

  /**
   * @generated from field: repeated zitadel.app.v2beta.OIDCResponseType response_types = 2;
   */
  responseTypes: OIDCResponseType[];

  /**
   * @generated from field: repeated zitadel.app.v2beta.OIDCGrantType grant_types = 3;
   */
  grantTypes: OIDCGrantType[];

  /**
   * @generated from field: zitadel.app.v2beta.OIDCAppType app_type = 4;
   */
  appType: OIDCAppType;

  /**
   * @generated from field: zitadel.app.v2beta.OIDCAuthMethodType auth_method_type = 5;
   */
  authMethodType: OIDCAuthMethodType;

  /**
   * ZITADEL will redirect to this link after a successful logout
   *
   * @generated from field: repeated string post_logout_redirect_uris = 6;
   */
  postLogoutRedirectUris: string[];

  /**
   * @generated from field: zitadel.app.v2beta.OIDCVersion version = 7;
   */
  version: OIDCVersion;

  /**
   * @generated from field: bool dev_mode = 8;
   */
  devMode: boolean;

  /**
   * @generated from field: zitadel.app.v2beta.OIDCTokenType access_token_type = 9;
   */
  accessTokenType: OIDCTokenType;

  /**
   * @generated from field: bool access_token_role_assertion = 10;
   */
  accessTokenRoleAssertion: boolean;

  /**
   * @generated from field: bool id_token_role_assertion = 11;
   */
  idTokenRoleAssertion: boolean;

  /**
   * @generated from field: bool id_token_userinfo_assertion = 12;
   */
  idTokenUserinfoAssertion: boolean;

  /**
   * @generated from field: google.protobuf.Duration clock_skew = 13;
   */
  clockSkew?: Duration;

  /**
   * @generated from field: repeated string additional_origins = 14;
   */
  additionalOrigins: string[];

  /**
   * @generated from field: bool skip_native_app_success_page = 15;
   */
  skipNativeAppSuccessPage: boolean;

  /**
   * @generated from field: string back_channel_logout_uri = 16;
   */
  backChannelLogoutUri: string;

  /**
   * @generated from field: zitadel.app.v2beta.LoginVersion login_version = 17;
   */
  loginVersion?: LoginVersion;
};

/**
 * @generated from message zitadel.app.v2beta.CreateOIDCApplicationRequest
 */
export declare type CreateOIDCApplicationRequestJson = {
  /**
   * Callback URI of the authorization request where the code or tokens will be sent to
   *
   * @generated from field: repeated string redirect_uris = 1;
   */
  redirectUris?: string[];

  /**
   * @generated from field: repeated zitadel.app.v2beta.OIDCResponseType response_types = 2;
   */
  responseTypes?: OIDCResponseTypeJson[];

  /**
   * @generated from field: repeated zitadel.app.v2beta.OIDCGrantType grant_types = 3;
   */
  grantTypes?: OIDCGrantTypeJson[];

  /**
   * @generated from field: zitadel.app.v2beta.OIDCAppType app_type = 4;
   */
  appType?: OIDCAppTypeJson;

  /**
   * @generated from field: zitadel.app.v2beta.OIDCAuthMethodType auth_method_type = 5;
   */
  authMethodType?: OIDCAuthMethodTypeJson;

  /**
   * ZITADEL will redirect to this link after a successful logout
   *
   * @generated from field: repeated string post_logout_redirect_uris = 6;
   */
  postLogoutRedirectUris?: string[];

  /**
   * @generated from field: zitadel.app.v2beta.OIDCVersion version = 7;
   */
  version?: OIDCVersionJson;

  /**
   * @generated from field: bool dev_mode = 8;
   */
  devMode?: boolean;

  /**
   * @generated from field: zitadel.app.v2beta.OIDCTokenType access_token_type = 9;
   */
  accessTokenType?: OIDCTokenTypeJson;

  /**
   * @generated from field: bool access_token_role_assertion = 10;
   */
  accessTokenRoleAssertion?: boolean;

  /**
   * @generated from field: bool id_token_role_assertion = 11;
   */
  idTokenRoleAssertion?: boolean;

  /**
   * @generated from field: bool id_token_userinfo_assertion = 12;
   */
  idTokenUserinfoAssertion?: boolean;

  /**
   * @generated from field: google.protobuf.Duration clock_skew = 13;
   */
  clockSkew?: DurationJson;

  /**
   * @generated from field: repeated string additional_origins = 14;
   */
  additionalOrigins?: string[];

  /**
   * @generated from field: bool skip_native_app_success_page = 15;
   */
  skipNativeAppSuccessPage?: boolean;

  /**
   * @generated from field: string back_channel_logout_uri = 16;
   */
  backChannelLogoutUri?: string;

  /**
   * @generated from field: zitadel.app.v2beta.LoginVersion login_version = 17;
   */
  loginVersion?: LoginVersionJson;
};

/**
 * Describes the message zitadel.app.v2beta.CreateOIDCApplicationRequest.
 * Use `create(CreateOIDCApplicationRequestSchema)` to create a new message.
 */
export declare const CreateOIDCApplicationRequestSchema: GenMessage<CreateOIDCApplicationRequest, {jsonType: CreateOIDCApplicationRequestJson}>;

/**
 * @generated from message zitadel.app.v2beta.CreateOIDCApplicationResponse
 */
export declare type CreateOIDCApplicationResponse = Message<"zitadel.app.v2beta.CreateOIDCApplicationResponse"> & {
  /**
   * @generated from field: string client_id = 1;
   */
  clientId: string;

  /**
   * @generated from field: string client_secret = 2;
   */
  clientSecret: string;

  /**
   * @generated from field: bool none_compliant = 3;
   */
  noneCompliant: boolean;

  /**
   * @generated from field: repeated zitadel.app.v2beta.OIDCLocalizedMessage compliance_problems = 4;
   */
  complianceProblems: OIDCLocalizedMessage[];
};

/**
 * @generated from message zitadel.app.v2beta.CreateOIDCApplicationResponse
 */
export declare type CreateOIDCApplicationResponseJson = {
  /**
   * @generated from field: string client_id = 1;
   */
  clientId?: string;

  /**
   * @generated from field: string client_secret = 2;
   */
  clientSecret?: string;

  /**
   * @generated from field: bool none_compliant = 3;
   */
  noneCompliant?: boolean;

  /**
   * @generated from field: repeated zitadel.app.v2beta.OIDCLocalizedMessage compliance_problems = 4;
   */
  complianceProblems?: OIDCLocalizedMessageJson[];
};

/**
 * Describes the message zitadel.app.v2beta.CreateOIDCApplicationResponse.
 * Use `create(CreateOIDCApplicationResponseSchema)` to create a new message.
 */
export declare const CreateOIDCApplicationResponseSchema: GenMessage<CreateOIDCApplicationResponse, {jsonType: CreateOIDCApplicationResponseJson}>;

/**
 * @generated from message zitadel.app.v2beta.CreateSAMLApplicationRequest
 */
export declare type CreateSAMLApplicationRequest = Message<"zitadel.app.v2beta.CreateSAMLApplicationRequest"> & {
  /**
   * @generated from oneof zitadel.app.v2beta.CreateSAMLApplicationRequest.metadata
   */
  metadata: {
    /**
     * @generated from field: bytes metadata_xml = 1;
     */
    value: Uint8Array;
    case: "metadataXml";
  } | {
    /**
     * @generated from field: string metadata_url = 2;
     */
    value: string;
    case: "metadataUrl";
  } | { case: undefined; value?: undefined };

  /**
   * @generated from field: zitadel.app.v2beta.LoginVersion login_version = 3;
   */
  loginVersion?: LoginVersion;
};

/**
 * @generated from message zitadel.app.v2beta.CreateSAMLApplicationRequest
 */
export declare type CreateSAMLApplicationRequestJson = {
  /**
   * @generated from field: bytes metadata_xml = 1;
   */
  metadataXml?: string;

  /**
   * @generated from field: string metadata_url = 2;
   */
  metadataUrl?: string;

  /**
   * @generated from field: zitadel.app.v2beta.LoginVersion login_version = 3;
   */
  loginVersion?: LoginVersionJson;
};

/**
 * Describes the message zitadel.app.v2beta.CreateSAMLApplicationRequest.
 * Use `create(CreateSAMLApplicationRequestSchema)` to create a new message.
 */
export declare const CreateSAMLApplicationRequestSchema: GenMessage<CreateSAMLApplicationRequest, {jsonType: CreateSAMLApplicationRequestJson}>;

/**
 * @generated from message zitadel.app.v2beta.CreateSAMLApplicationResponse
 */
export declare type CreateSAMLApplicationResponse = Message<"zitadel.app.v2beta.CreateSAMLApplicationResponse"> & {
};

/**
 * @generated from message zitadel.app.v2beta.CreateSAMLApplicationResponse
 */
export declare type CreateSAMLApplicationResponseJson = {
};

/**
 * Describes the message zitadel.app.v2beta.CreateSAMLApplicationResponse.
 * Use `create(CreateSAMLApplicationResponseSchema)` to create a new message.
 */
export declare const CreateSAMLApplicationResponseSchema: GenMessage<CreateSAMLApplicationResponse, {jsonType: CreateSAMLApplicationResponseJson}>;

/**
 * @generated from message zitadel.app.v2beta.CreateAPIApplicationRequest
 */
export declare type CreateAPIApplicationRequest = Message<"zitadel.app.v2beta.CreateAPIApplicationRequest"> & {
  /**
   * @generated from field: zitadel.app.v2beta.APIAuthMethodType auth_method_type = 1;
   */
  authMethodType: APIAuthMethodType;
};

/**
 * @generated from message zitadel.app.v2beta.CreateAPIApplicationRequest
 */
export declare type CreateAPIApplicationRequestJson = {
  /**
   * @generated from field: zitadel.app.v2beta.APIAuthMethodType auth_method_type = 1;
   */
  authMethodType?: APIAuthMethodTypeJson;
};

/**
 * Describes the message zitadel.app.v2beta.CreateAPIApplicationRequest.
 * Use `create(CreateAPIApplicationRequestSchema)` to create a new message.
 */
export declare const CreateAPIApplicationRequestSchema: GenMessage<CreateAPIApplicationRequest, {jsonType: CreateAPIApplicationRequestJson}>;

/**
 * @generated from message zitadel.app.v2beta.CreateAPIApplicationResponse
 */
export declare type CreateAPIApplicationResponse = Message<"zitadel.app.v2beta.CreateAPIApplicationResponse"> & {
  /**
   * @generated from field: string client_id = 1;
   */
  clientId: string;

  /**
   * @generated from field: string client_secret = 2;
   */
  clientSecret: string;
};

/**
 * @generated from message zitadel.app.v2beta.CreateAPIApplicationResponse
 */
export declare type CreateAPIApplicationResponseJson = {
  /**
   * @generated from field: string client_id = 1;
   */
  clientId?: string;

  /**
   * @generated from field: string client_secret = 2;
   */
  clientSecret?: string;
};

/**
 * Describes the message zitadel.app.v2beta.CreateAPIApplicationResponse.
 * Use `create(CreateAPIApplicationResponseSchema)` to create a new message.
 */
export declare const CreateAPIApplicationResponseSchema: GenMessage<CreateAPIApplicationResponse, {jsonType: CreateAPIApplicationResponseJson}>;

/**
 * @generated from message zitadel.app.v2beta.UpdateApplicationRequest
 */
export declare type UpdateApplicationRequest = Message<"zitadel.app.v2beta.UpdateApplicationRequest"> & {
  /**
   * @generated from field: string project_id = 1;
   */
  projectId: string;

  /**
   * @generated from field: string id = 2;
   */
  id: string;

  /**
   * @generated from field: string name = 3;
   */
  name: string;

  /**
   * @generated from oneof zitadel.app.v2beta.UpdateApplicationRequest.update_request_type
   */
  updateRequestType: {
    /**
     * @generated from field: zitadel.app.v2beta.UpdateSAMLApplicationConfigurationRequest saml_configuration_request = 4;
     */
    value: UpdateSAMLApplicationConfigurationRequest;
    case: "samlConfigurationRequest";
  } | {
    /**
     * @generated from field: zitadel.app.v2beta.UpdateOIDCApplicationConfigurationRequest oidc_configuration_request = 5;
     */
    value: UpdateOIDCApplicationConfigurationRequest;
    case: "oidcConfigurationRequest";
  } | {
    /**
     * @generated from field: zitadel.app.v2beta.UpdateAPIApplicationConfigurationRequest api_configuration_request = 6;
     */
    value: UpdateAPIApplicationConfigurationRequest;
    case: "apiConfigurationRequest";
  } | { case: undefined; value?: undefined };
};

/**
 * @generated from message zitadel.app.v2beta.UpdateApplicationRequest
 */
export declare type UpdateApplicationRequestJson = {
  /**
   * @generated from field: string project_id = 1;
   */
  projectId?: string;

  /**
   * @generated from field: string id = 2;
   */
  id?: string;

  /**
   * @generated from field: string name = 3;
   */
  name?: string;

  /**
   * @generated from field: zitadel.app.v2beta.UpdateSAMLApplicationConfigurationRequest saml_configuration_request = 4;
   */
  samlConfigurationRequest?: UpdateSAMLApplicationConfigurationRequestJson;

  /**
   * @generated from field: zitadel.app.v2beta.UpdateOIDCApplicationConfigurationRequest oidc_configuration_request = 5;
   */
  oidcConfigurationRequest?: UpdateOIDCApplicationConfigurationRequestJson;

  /**
   * @generated from field: zitadel.app.v2beta.UpdateAPIApplicationConfigurationRequest api_configuration_request = 6;
   */
  apiConfigurationRequest?: UpdateAPIApplicationConfigurationRequestJson;
};

/**
 * Describes the message zitadel.app.v2beta.UpdateApplicationRequest.
 * Use `create(UpdateApplicationRequestSchema)` to create a new message.
 */
export declare const UpdateApplicationRequestSchema: GenMessage<UpdateApplicationRequest, {jsonType: UpdateApplicationRequestJson}>;

/**
 * @generated from message zitadel.app.v2beta.UpdateApplicationResponse
 */
export declare type UpdateApplicationResponse = Message<"zitadel.app.v2beta.UpdateApplicationResponse"> & {
  /**
   * The timestamp of the app update.
   *
   * @generated from field: google.protobuf.Timestamp change_date = 2;
   */
  changeDate?: Timestamp;
};

/**
 * @generated from message zitadel.app.v2beta.UpdateApplicationResponse
 */
export declare type UpdateApplicationResponseJson = {
  /**
   * The timestamp of the app update.
   *
   * @generated from field: google.protobuf.Timestamp change_date = 2;
   */
  changeDate?: TimestampJson;
};

/**
 * Describes the message zitadel.app.v2beta.UpdateApplicationResponse.
 * Use `create(UpdateApplicationResponseSchema)` to create a new message.
 */
export declare const UpdateApplicationResponseSchema: GenMessage<UpdateApplicationResponse, {jsonType: UpdateApplicationResponseJson}>;

/**
 * @generated from message zitadel.app.v2beta.UpdateSAMLApplicationConfigurationRequest
 */
export declare type UpdateSAMLApplicationConfigurationRequest = Message<"zitadel.app.v2beta.UpdateSAMLApplicationConfigurationRequest"> & {
  /**
   * @generated from oneof zitadel.app.v2beta.UpdateSAMLApplicationConfigurationRequest.metadata
   */
  metadata: {
    /**
     * @generated from field: bytes metadata_xml = 1;
     */
    value: Uint8Array;
    case: "metadataXml";
  } | {
    /**
     * @generated from field: string metadata_url = 2;
     */
    value: string;
    case: "metadataUrl";
  } | { case: undefined; value?: undefined };

  /**
   * @generated from field: optional zitadel.app.v2beta.LoginVersion login_version = 3;
   */
  loginVersion?: LoginVersion;
};

/**
 * @generated from message zitadel.app.v2beta.UpdateSAMLApplicationConfigurationRequest
 */
export declare type UpdateSAMLApplicationConfigurationRequestJson = {
  /**
   * @generated from field: bytes metadata_xml = 1;
   */
  metadataXml?: string;

  /**
   * @generated from field: string metadata_url = 2;
   */
  metadataUrl?: string;

  /**
   * @generated from field: optional zitadel.app.v2beta.LoginVersion login_version = 3;
   */
  loginVersion?: LoginVersionJson;
};

/**
 * Describes the message zitadel.app.v2beta.UpdateSAMLApplicationConfigurationRequest.
 * Use `create(UpdateSAMLApplicationConfigurationRequestSchema)` to create a new message.
 */
export declare const UpdateSAMLApplicationConfigurationRequestSchema: GenMessage<UpdateSAMLApplicationConfigurationRequest, {jsonType: UpdateSAMLApplicationConfigurationRequestJson}>;

/**
 * @generated from message zitadel.app.v2beta.UpdateOIDCApplicationConfigurationRequest
 */
export declare type UpdateOIDCApplicationConfigurationRequest = Message<"zitadel.app.v2beta.UpdateOIDCApplicationConfigurationRequest"> & {
  /**
   * @generated from field: repeated string redirect_uris = 1;
   */
  redirectUris: string[];

  /**
   * @generated from field: repeated zitadel.app.v2beta.OIDCResponseType response_types = 2;
   */
  responseTypes: OIDCResponseType[];

  /**
   * @generated from field: repeated zitadel.app.v2beta.OIDCGrantType grant_types = 3;
   */
  grantTypes: OIDCGrantType[];

  /**
   * @generated from field: optional zitadel.app.v2beta.OIDCAppType app_type = 4;
   */
  appType?: OIDCAppType;

  /**
   * @generated from field: optional zitadel.app.v2beta.OIDCAuthMethodType auth_method_type = 5;
   */
  authMethodType?: OIDCAuthMethodType;

  /**
   * @generated from field: repeated string post_logout_redirect_uris = 6;
   */
  postLogoutRedirectUris: string[];

  /**
   * @generated from field: optional zitadel.app.v2beta.OIDCVersion version = 7;
   */
  version?: OIDCVersion;

  /**
   * @generated from field: optional bool dev_mode = 8;
   */
  devMode?: boolean;

  /**
   * @generated from field: optional zitadel.app.v2beta.OIDCTokenType access_token_type = 9;
   */
  accessTokenType?: OIDCTokenType;

  /**
   * @generated from field: optional bool access_token_role_assertion = 10;
   */
  accessTokenRoleAssertion?: boolean;

  /**
   * @generated from field: optional bool id_token_role_assertion = 11;
   */
  idTokenRoleAssertion?: boolean;

  /**
   * @generated from field: optional bool id_token_userinfo_assertion = 12;
   */
  idTokenUserinfoAssertion?: boolean;

  /**
   * @generated from field: optional google.protobuf.Duration clock_skew = 13;
   */
  clockSkew?: Duration;

  /**
   * @generated from field: repeated string additional_origins = 14;
   */
  additionalOrigins: string[];

  /**
   * @generated from field: optional bool skip_native_app_success_page = 15;
   */
  skipNativeAppSuccessPage?: boolean;

  /**
   * @generated from field: optional string back_channel_logout_uri = 16;
   */
  backChannelLogoutUri?: string;

  /**
   * @generated from field: optional zitadel.app.v2beta.LoginVersion login_version = 17;
   */
  loginVersion?: LoginVersion;
};

/**
 * @generated from message zitadel.app.v2beta.UpdateOIDCApplicationConfigurationRequest
 */
export declare type UpdateOIDCApplicationConfigurationRequestJson = {
  /**
   * @generated from field: repeated string redirect_uris = 1;
   */
  redirectUris?: string[];

  /**
   * @generated from field: repeated zitadel.app.v2beta.OIDCResponseType response_types = 2;
   */
  responseTypes?: OIDCResponseTypeJson[];

  /**
   * @generated from field: repeated zitadel.app.v2beta.OIDCGrantType grant_types = 3;
   */
  grantTypes?: OIDCGrantTypeJson[];

  /**
   * @generated from field: optional zitadel.app.v2beta.OIDCAppType app_type = 4;
   */
  appType?: OIDCAppTypeJson;

  /**
   * @generated from field: optional zitadel.app.v2beta.OIDCAuthMethodType auth_method_type = 5;
   */
  authMethodType?: OIDCAuthMethodTypeJson;

  /**
   * @generated from field: repeated string post_logout_redirect_uris = 6;
   */
  postLogoutRedirectUris?: string[];

  /**
   * @generated from field: optional zitadel.app.v2beta.OIDCVersion version = 7;
   */
  version?: OIDCVersionJson;

  /**
   * @generated from field: optional bool dev_mode = 8;
   */
  devMode?: boolean;

  /**
   * @generated from field: optional zitadel.app.v2beta.OIDCTokenType access_token_type = 9;
   */
  accessTokenType?: OIDCTokenTypeJson;

  /**
   * @generated from field: optional bool access_token_role_assertion = 10;
   */
  accessTokenRoleAssertion?: boolean;

  /**
   * @generated from field: optional bool id_token_role_assertion = 11;
   */
  idTokenRoleAssertion?: boolean;

  /**
   * @generated from field: optional bool id_token_userinfo_assertion = 12;
   */
  idTokenUserinfoAssertion?: boolean;

  /**
   * @generated from field: optional google.protobuf.Duration clock_skew = 13;
   */
  clockSkew?: DurationJson;

  /**
   * @generated from field: repeated string additional_origins = 14;
   */
  additionalOrigins?: string[];

  /**
   * @generated from field: optional bool skip_native_app_success_page = 15;
   */
  skipNativeAppSuccessPage?: boolean;

  /**
   * @generated from field: optional string back_channel_logout_uri = 16;
   */
  backChannelLogoutUri?: string;

  /**
   * @generated from field: optional zitadel.app.v2beta.LoginVersion login_version = 17;
   */
  loginVersion?: LoginVersionJson;
};

/**
 * Describes the message zitadel.app.v2beta.UpdateOIDCApplicationConfigurationRequest.
 * Use `create(UpdateOIDCApplicationConfigurationRequestSchema)` to create a new message.
 */
export declare const UpdateOIDCApplicationConfigurationRequestSchema: GenMessage<UpdateOIDCApplicationConfigurationRequest, {jsonType: UpdateOIDCApplicationConfigurationRequestJson}>;

/**
 * @generated from message zitadel.app.v2beta.UpdateAPIApplicationConfigurationRequest
 */
export declare type UpdateAPIApplicationConfigurationRequest = Message<"zitadel.app.v2beta.UpdateAPIApplicationConfigurationRequest"> & {
  /**
   * @generated from field: zitadel.app.v2beta.APIAuthMethodType auth_method_type = 1;
   */
  authMethodType: APIAuthMethodType;
};

/**
 * @generated from message zitadel.app.v2beta.UpdateAPIApplicationConfigurationRequest
 */
export declare type UpdateAPIApplicationConfigurationRequestJson = {
  /**
   * @generated from field: zitadel.app.v2beta.APIAuthMethodType auth_method_type = 1;
   */
  authMethodType?: APIAuthMethodTypeJson;
};

/**
 * Describes the message zitadel.app.v2beta.UpdateAPIApplicationConfigurationRequest.
 * Use `create(UpdateAPIApplicationConfigurationRequestSchema)` to create a new message.
 */
export declare const UpdateAPIApplicationConfigurationRequestSchema: GenMessage<UpdateAPIApplicationConfigurationRequest, {jsonType: UpdateAPIApplicationConfigurationRequestJson}>;

/**
 * @generated from message zitadel.app.v2beta.GetApplicationRequest
 */
export declare type GetApplicationRequest = Message<"zitadel.app.v2beta.GetApplicationRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * @generated from message zitadel.app.v2beta.GetApplicationRequest
 */
export declare type GetApplicationRequestJson = {
  /**
   * @generated from field: string id = 1;
   */
  id?: string;
};

/**
 * Describes the message zitadel.app.v2beta.GetApplicationRequest.
 * Use `create(GetApplicationRequestSchema)` to create a new message.
 */
export declare const GetApplicationRequestSchema: GenMessage<GetApplicationRequest, {jsonType: GetApplicationRequestJson}>;

/**
 * @generated from message zitadel.app.v2beta.GetApplicationResponse
 */
export declare type GetApplicationResponse = Message<"zitadel.app.v2beta.GetApplicationResponse"> & {
  /**
   * @generated from field: zitadel.app.v2beta.Application app = 1;
   */
  app?: Application;
};

/**
 * @generated from message zitadel.app.v2beta.GetApplicationResponse
 */
export declare type GetApplicationResponseJson = {
  /**
   * @generated from field: zitadel.app.v2beta.Application app = 1;
   */
  app?: ApplicationJson;
};

/**
 * Describes the message zitadel.app.v2beta.GetApplicationResponse.
 * Use `create(GetApplicationResponseSchema)` to create a new message.
 */
export declare const GetApplicationResponseSchema: GenMessage<GetApplicationResponse, {jsonType: GetApplicationResponseJson}>;

/**
 * @generated from message zitadel.app.v2beta.DeleteApplicationRequest
 */
export declare type DeleteApplicationRequest = Message<"zitadel.app.v2beta.DeleteApplicationRequest"> & {
  /**
   * @generated from field: string project_id = 1;
   */
  projectId: string;

  /**
   * @generated from field: string id = 2;
   */
  id: string;
};

/**
 * @generated from message zitadel.app.v2beta.DeleteApplicationRequest
 */
export declare type DeleteApplicationRequestJson = {
  /**
   * @generated from field: string project_id = 1;
   */
  projectId?: string;

  /**
   * @generated from field: string id = 2;
   */
  id?: string;
};

/**
 * Describes the message zitadel.app.v2beta.DeleteApplicationRequest.
 * Use `create(DeleteApplicationRequestSchema)` to create a new message.
 */
export declare const DeleteApplicationRequestSchema: GenMessage<DeleteApplicationRequest, {jsonType: DeleteApplicationRequestJson}>;

/**
 * @generated from message zitadel.app.v2beta.DeleteApplicationResponse
 */
export declare type DeleteApplicationResponse = Message<"zitadel.app.v2beta.DeleteApplicationResponse"> & {
  /**
   * @generated from field: google.protobuf.Timestamp deletion_date = 1;
   */
  deletionDate?: Timestamp;
};

/**
 * @generated from message zitadel.app.v2beta.DeleteApplicationResponse
 */
export declare type DeleteApplicationResponseJson = {
  /**
   * @generated from field: google.protobuf.Timestamp deletion_date = 1;
   */
  deletionDate?: TimestampJson;
};

/**
 * Describes the message zitadel.app.v2beta.DeleteApplicationResponse.
 * Use `create(DeleteApplicationResponseSchema)` to create a new message.
 */
export declare const DeleteApplicationResponseSchema: GenMessage<DeleteApplicationResponse, {jsonType: DeleteApplicationResponseJson}>;

/**
 * @generated from message zitadel.app.v2beta.DeactivateApplicationRequest
 */
export declare type DeactivateApplicationRequest = Message<"zitadel.app.v2beta.DeactivateApplicationRequest"> & {
  /**
   * @generated from field: string project_id = 1;
   */
  projectId: string;

  /**
   * @generated from field: string id = 2;
   */
  id: string;
};

/**
 * @generated from message zitadel.app.v2beta.DeactivateApplicationRequest
 */
export declare type DeactivateApplicationRequestJson = {
  /**
   * @generated from field: string project_id = 1;
   */
  projectId?: string;

  /**
   * @generated from field: string id = 2;
   */
  id?: string;
};

/**
 * Describes the message zitadel.app.v2beta.DeactivateApplicationRequest.
 * Use `create(DeactivateApplicationRequestSchema)` to create a new message.
 */
export declare const DeactivateApplicationRequestSchema: GenMessage<DeactivateApplicationRequest, {jsonType: DeactivateApplicationRequestJson}>;

/**
 * @generated from message zitadel.app.v2beta.DeactivateApplicationResponse
 */
export declare type DeactivateApplicationResponse = Message<"zitadel.app.v2beta.DeactivateApplicationResponse"> & {
  /**
   * @generated from field: google.protobuf.Timestamp deactivation_date = 1;
   */
  deactivationDate?: Timestamp;
};

/**
 * @generated from message zitadel.app.v2beta.DeactivateApplicationResponse
 */
export declare type DeactivateApplicationResponseJson = {
  /**
   * @generated from field: google.protobuf.Timestamp deactivation_date = 1;
   */
  deactivationDate?: TimestampJson;
};

/**
 * Describes the message zitadel.app.v2beta.DeactivateApplicationResponse.
 * Use `create(DeactivateApplicationResponseSchema)` to create a new message.
 */
export declare const DeactivateApplicationResponseSchema: GenMessage<DeactivateApplicationResponse, {jsonType: DeactivateApplicationResponseJson}>;

/**
 * @generated from message zitadel.app.v2beta.ReactivateApplicationRequest
 */
export declare type ReactivateApplicationRequest = Message<"zitadel.app.v2beta.ReactivateApplicationRequest"> & {
  /**
   * @generated from field: string project_id = 1;
   */
  projectId: string;

  /**
   * @generated from field: string id = 2;
   */
  id: string;
};

/**
 * @generated from message zitadel.app.v2beta.ReactivateApplicationRequest
 */
export declare type ReactivateApplicationRequestJson = {
  /**
   * @generated from field: string project_id = 1;
   */
  projectId?: string;

  /**
   * @generated from field: string id = 2;
   */
  id?: string;
};

/**
 * Describes the message zitadel.app.v2beta.ReactivateApplicationRequest.
 * Use `create(ReactivateApplicationRequestSchema)` to create a new message.
 */
export declare const ReactivateApplicationRequestSchema: GenMessage<ReactivateApplicationRequest, {jsonType: ReactivateApplicationRequestJson}>;

/**
 * @generated from message zitadel.app.v2beta.ReactivateApplicationResponse
 */
export declare type ReactivateApplicationResponse = Message<"zitadel.app.v2beta.ReactivateApplicationResponse"> & {
  /**
   * @generated from field: google.protobuf.Timestamp reactivation_date = 1;
   */
  reactivationDate?: Timestamp;
};

/**
 * @generated from message zitadel.app.v2beta.ReactivateApplicationResponse
 */
export declare type ReactivateApplicationResponseJson = {
  /**
   * @generated from field: google.protobuf.Timestamp reactivation_date = 1;
   */
  reactivationDate?: TimestampJson;
};

/**
 * Describes the message zitadel.app.v2beta.ReactivateApplicationResponse.
 * Use `create(ReactivateApplicationResponseSchema)` to create a new message.
 */
export declare const ReactivateApplicationResponseSchema: GenMessage<ReactivateApplicationResponse, {jsonType: ReactivateApplicationResponseJson}>;

/**
 * @generated from message zitadel.app.v2beta.RegenerateClientSecretRequest
 */
export declare type RegenerateClientSecretRequest = Message<"zitadel.app.v2beta.RegenerateClientSecretRequest"> & {
  /**
   * @generated from field: string project_id = 1;
   */
  projectId: string;

  /**
   * @generated from field: string application_id = 2;
   */
  applicationId: string;

  /**
   * @generated from oneof zitadel.app.v2beta.RegenerateClientSecretRequest.app_type
   */
  appType: {
    /**
     * @generated from field: bool is_oidc = 3;
     */
    value: boolean;
    case: "isOidc";
  } | {
    /**
     * @generated from field: bool is_api = 4;
     */
    value: boolean;
    case: "isApi";
  } | { case: undefined; value?: undefined };
};

/**
 * @generated from message zitadel.app.v2beta.RegenerateClientSecretRequest
 */
export declare type RegenerateClientSecretRequestJson = {
  /**
   * @generated from field: string project_id = 1;
   */
  projectId?: string;

  /**
   * @generated from field: string application_id = 2;
   */
  applicationId?: string;

  /**
   * @generated from field: bool is_oidc = 3;
   */
  isOidc?: boolean;

  /**
   * @generated from field: bool is_api = 4;
   */
  isApi?: boolean;
};

/**
 * Describes the message zitadel.app.v2beta.RegenerateClientSecretRequest.
 * Use `create(RegenerateClientSecretRequestSchema)` to create a new message.
 */
export declare const RegenerateClientSecretRequestSchema: GenMessage<RegenerateClientSecretRequest, {jsonType: RegenerateClientSecretRequestJson}>;

/**
 * @generated from message zitadel.app.v2beta.RegenerateClientSecretResponse
 */
export declare type RegenerateClientSecretResponse = Message<"zitadel.app.v2beta.RegenerateClientSecretResponse"> & {
  /**
   * @generated from field: string client_secret = 1;
   */
  clientSecret: string;

  /**
   * The timestamp of the creation of the new client secret
   *
   * @generated from field: google.protobuf.Timestamp creation_date = 2;
   */
  creationDate?: Timestamp;
};

/**
 * @generated from message zitadel.app.v2beta.RegenerateClientSecretResponse
 */
export declare type RegenerateClientSecretResponseJson = {
  /**
   * @generated from field: string client_secret = 1;
   */
  clientSecret?: string;

  /**
   * The timestamp of the creation of the new client secret
   *
   * @generated from field: google.protobuf.Timestamp creation_date = 2;
   */
  creationDate?: TimestampJson;
};

/**
 * Describes the message zitadel.app.v2beta.RegenerateClientSecretResponse.
 * Use `create(RegenerateClientSecretResponseSchema)` to create a new message.
 */
export declare const RegenerateClientSecretResponseSchema: GenMessage<RegenerateClientSecretResponse, {jsonType: RegenerateClientSecretResponseJson}>;

/**
 * @generated from message zitadel.app.v2beta.ListApplicationsRequest
 */
export declare type ListApplicationsRequest = Message<"zitadel.app.v2beta.ListApplicationsRequest"> & {
  /**
   * @generated from field: string project_id = 1;
   */
  projectId: string;

  /**
   * Pagination and sorting.
   *
   * @generated from field: zitadel.filter.v2.PaginationRequest pagination = 2;
   */
  pagination?: PaginationRequest;

  /**
   * criteria the client is looking for
   *
   * @generated from field: repeated zitadel.app.v2beta.ApplicationSearchFilter filters = 3;
   */
  filters: ApplicationSearchFilter[];

  /**
   * @generated from field: zitadel.app.v2beta.AppSorting sorting_column = 4;
   */
  sortingColumn: AppSorting;
};

/**
 * @generated from message zitadel.app.v2beta.ListApplicationsRequest
 */
export declare type ListApplicationsRequestJson = {
  /**
   * @generated from field: string project_id = 1;
   */
  projectId?: string;

  /**
   * Pagination and sorting.
   *
   * @generated from field: zitadel.filter.v2.PaginationRequest pagination = 2;
   */
  pagination?: PaginationRequestJson;

  /**
   * criteria the client is looking for
   *
   * @generated from field: repeated zitadel.app.v2beta.ApplicationSearchFilter filters = 3;
   */
  filters?: ApplicationSearchFilterJson[];

  /**
   * @generated from field: zitadel.app.v2beta.AppSorting sorting_column = 4;
   */
  sortingColumn?: AppSortingJson;
};

/**
 * Describes the message zitadel.app.v2beta.ListApplicationsRequest.
 * Use `create(ListApplicationsRequestSchema)` to create a new message.
 */
export declare const ListApplicationsRequestSchema: GenMessage<ListApplicationsRequest, {jsonType: ListApplicationsRequestJson}>;

/**
 * @generated from message zitadel.app.v2beta.ListApplicationsResponse
 */
export declare type ListApplicationsResponse = Message<"zitadel.app.v2beta.ListApplicationsResponse"> & {
  /**
   * @generated from field: repeated zitadel.app.v2beta.Application applications = 1;
   */
  applications: Application[];

  /**
   * Contains the total number of apps matching the query and the applied limit.
   *
   * @generated from field: zitadel.filter.v2.PaginationResponse pagination = 2;
   */
  pagination?: PaginationResponse;
};

/**
 * @generated from message zitadel.app.v2beta.ListApplicationsResponse
 */
export declare type ListApplicationsResponseJson = {
  /**
   * @generated from field: repeated zitadel.app.v2beta.Application applications = 1;
   */
  applications?: ApplicationJson[];

  /**
   * Contains the total number of apps matching the query and the applied limit.
   *
   * @generated from field: zitadel.filter.v2.PaginationResponse pagination = 2;
   */
  pagination?: PaginationResponseJson;
};

/**
 * Describes the message zitadel.app.v2beta.ListApplicationsResponse.
 * Use `create(ListApplicationsResponseSchema)` to create a new message.
 */
export declare const ListApplicationsResponseSchema: GenMessage<ListApplicationsResponse, {jsonType: ListApplicationsResponseJson}>;

/**
 * Service to manage apps.
 * The service provides methods to create, update, delete and list apps and app keys.
 *
 * @generated from service zitadel.app.v2beta.AppService
 */
export declare const AppService: GenService<{
  /**
   * Create Application
   *
   * Create an application. The application can be OIDC, API or SAML type, based on the input.
   *
   * The user needs to have project.app.write permission
   *
   * Required permissions:
   *   - project.app.write
   *
   * @generated from rpc zitadel.app.v2beta.AppService.CreateApplication
   */
  createApplication: {
    methodKind: "unary";
    input: typeof CreateApplicationRequestSchema;
    output: typeof CreateApplicationResponseSchema;
  },
  /**
   * Update Application
   *
   * Changes the configuration of an OIDC, API or SAML type application, as well as
   * the application name, based on the input provided.
   *
   * The user needs to have project.app.write permission
   *
   * Required permissions:
   *   - project.app.write
   *
   * @generated from rpc zitadel.app.v2beta.AppService.UpdateApplication
   */
  updateApplication: {
    methodKind: "unary";
    input: typeof UpdateApplicationRequestSchema;
    output: typeof UpdateApplicationResponseSchema;
  },
  /**
   * Get Application
   *
   * Retrieves the application matching the provided ID.
   *
   * The user needs to have project.app.read permission
   *
   * Required permissions:
   *   - project.app.read
   *
   * @generated from rpc zitadel.app.v2beta.AppService.GetApplication
   */
  getApplication: {
    methodKind: "unary";
    input: typeof GetApplicationRequestSchema;
    output: typeof GetApplicationResponseSchema;
  },
  /**
   * Delete Application
   *
   * Deletes the application belonging to the input project and matching the provided
   * application ID
   *
   * The user needs to have project.app.delete permission
   *
   * Required permissions:
   *   - project.app.delete
   *
   * @generated from rpc zitadel.app.v2beta.AppService.DeleteApplication
   */
  deleteApplication: {
    methodKind: "unary";
    input: typeof DeleteApplicationRequestSchema;
    output: typeof DeleteApplicationResponseSchema;
  },
  /**
   * Deactivate Application
   *
   * Deactivates the application belonging to the input project and matching the provided
   * application ID
   *
   * The user needs to have project.app.write permission
   *
   * Required permissions:
   *   - project.app.write
   *
   * @generated from rpc zitadel.app.v2beta.AppService.DeactivateApplication
   */
  deactivateApplication: {
    methodKind: "unary";
    input: typeof DeactivateApplicationRequestSchema;
    output: typeof DeactivateApplicationResponseSchema;
  },
  /**
   * Reactivate Application
   *
   * Reactivates the application belonging to the input project and matching the provided
   * application ID
   *
   * The user needs to have project.app.write permission
   *
   * Required permissions:
   *   - project.app.write
   *
   * @generated from rpc zitadel.app.v2beta.AppService.ReactivateApplication
   */
  reactivateApplication: {
    methodKind: "unary";
    input: typeof ReactivateApplicationRequestSchema;
    output: typeof ReactivateApplicationResponseSchema;
  },
  /**
   * Regenerate Client Secret
   *
   * Regenerates the client secret of an API or OIDC application that belongs to the input project.
   *
   * The user needs to have project.app.write permission
   *
   * Required permissions:
   *   - project.app.write
   *
   * @generated from rpc zitadel.app.v2beta.AppService.RegenerateClientSecret
   */
  regenerateClientSecret: {
    methodKind: "unary";
    input: typeof RegenerateClientSecretRequestSchema;
    output: typeof RegenerateClientSecretResponseSchema;
  },
  /**
   * List Applications
   *
   * Returns a list of applications matching the input parameters that belong to the provided
   * project.
   *
   * The result can be sorted by app id, name, creation date, change date or state. It can also
   * be filtered by app state, app type and app name.
   *
   * The user needs to have project.app.read permission
   *
   * Required permissions:
   *   - project.app.read
   *
   * @generated from rpc zitadel.app.v2beta.AppService.ListApplications
   */
  listApplications: {
    methodKind: "unary";
    input: typeof ListApplicationsRequestSchema;
    output: typeof ListApplicationsResponseSchema;
  },
}>;

