// @generated by protoc-gen-es v2.6.0 with parameter "json_types=true,import_extension=js"
// @generated from file zitadel/settings/v2/lockout_settings.proto (package zitadel.settings.v2, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { ResourceOwnerType, ResourceOwnerTypeJson } from "./settings_pb.js";

/**
 * Describes the file zitadel/settings/v2/lockout_settings.proto.
 */
export declare const file_zitadel_settings_v2_lockout_settings: GenFile;

/**
 * @generated from message zitadel.settings.v2.LockoutSettings
 */
export declare type LockoutSettings = Message<"zitadel.settings.v2.LockoutSettings"> & {
  /**
   * @generated from field: uint64 max_password_attempts = 1;
   */
  maxPasswordAttempts: bigint;

  /**
   * resource_owner_type returns if the settings is managed on the organization or on the instance
   *
   * @generated from field: zitadel.settings.v2.ResourceOwnerType resource_owner_type = 2;
   */
  resourceOwnerType: ResourceOwnerType;

  /**
   * @generated from field: uint64 max_otp_attempts = 3;
   */
  maxOtpAttempts: bigint;
};

/**
 * @generated from message zitadel.settings.v2.LockoutSettings
 */
export declare type LockoutSettingsJson = {
  /**
   * @generated from field: uint64 max_password_attempts = 1;
   */
  maxPasswordAttempts?: string;

  /**
   * resource_owner_type returns if the settings is managed on the organization or on the instance
   *
   * @generated from field: zitadel.settings.v2.ResourceOwnerType resource_owner_type = 2;
   */
  resourceOwnerType?: ResourceOwnerTypeJson;

  /**
   * @generated from field: uint64 max_otp_attempts = 3;
   */
  maxOtpAttempts?: string;
};

/**
 * Describes the message zitadel.settings.v2.LockoutSettings.
 * Use `create(LockoutSettingsSchema)` to create a new message.
 */
export declare const LockoutSettingsSchema: GenMessage<LockoutSettings, {jsonType: LockoutSettingsJson}>;

