// @generated by protoc-gen-es v2.6.0 with parameter "json_types=true,import_extension=js"
// @generated from file zitadel/settings/v2/security_settings.proto (package zitadel.settings.v2, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file zitadel/settings/v2/security_settings.proto.
 */
export declare const file_zitadel_settings_v2_security_settings: GenFile;

/**
 * @generated from message zitadel.settings.v2.SecuritySettings
 */
export declare type SecuritySettings = Message<"zitadel.settings.v2.SecuritySettings"> & {
  /**
   * @generated from field: zitadel.settings.v2.EmbeddedIframeSettings embedded_iframe = 1;
   */
  embeddedIframe?: EmbeddedIframeSettings;

  /**
   * @generated from field: bool enable_impersonation = 2;
   */
  enableImpersonation: boolean;
};

/**
 * @generated from message zitadel.settings.v2.SecuritySettings
 */
export declare type SecuritySettingsJson = {
  /**
   * @generated from field: zitadel.settings.v2.EmbeddedIframeSettings embedded_iframe = 1;
   */
  embeddedIframe?: EmbeddedIframeSettingsJson;

  /**
   * @generated from field: bool enable_impersonation = 2;
   */
  enableImpersonation?: boolean;
};

/**
 * Describes the message zitadel.settings.v2.SecuritySettings.
 * Use `create(SecuritySettingsSchema)` to create a new message.
 */
export declare const SecuritySettingsSchema: GenMessage<SecuritySettings, {jsonType: SecuritySettingsJson}>;

/**
 * @generated from message zitadel.settings.v2.EmbeddedIframeSettings
 */
export declare type EmbeddedIframeSettings = Message<"zitadel.settings.v2.EmbeddedIframeSettings"> & {
  /**
   * @generated from field: bool enabled = 1;
   */
  enabled: boolean;

  /**
   * @generated from field: repeated string allowed_origins = 2;
   */
  allowedOrigins: string[];
};

/**
 * @generated from message zitadel.settings.v2.EmbeddedIframeSettings
 */
export declare type EmbeddedIframeSettingsJson = {
  /**
   * @generated from field: bool enabled = 1;
   */
  enabled?: boolean;

  /**
   * @generated from field: repeated string allowed_origins = 2;
   */
  allowedOrigins?: string[];
};

/**
 * Describes the message zitadel.settings.v2.EmbeddedIframeSettings.
 * Use `create(EmbeddedIframeSettingsSchema)` to create a new message.
 */
export declare const EmbeddedIframeSettingsSchema: GenMessage<EmbeddedIframeSettings, {jsonType: EmbeddedIframeSettingsJson}>;

