// @generated by protoc-gen-es v2.6.0 with parameter "json_types=true,import_extension=js"
// @generated from file zitadel/settings/v2/security_settings.proto (package zitadel.settings.v2, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_protoc_gen_openapiv2_options_annotations } from "../../../protoc-gen-openapiv2/options/annotations_pb.js";

/**
 * Describes the file zitadel/settings/v2/security_settings.proto.
 */
export const file_zitadel_settings_v2_security_settings = /*@__PURE__*/
  fileDesc("Cit6aXRhZGVsL3NldHRpbmdzL3YyL3NlY3VyaXR5X3NldHRpbmdzLnByb3RvEhN6aXRhZGVsLnNldHRpbmdzLnYyIqsBChBTZWN1cml0eVNldHRpbmdzEkQKD2VtYmVkZGVkX2lmcmFtZRgBIAEoCzIrLnppdGFkZWwuc2V0dGluZ3MudjIuRW1iZWRkZWRJZnJhbWVTZXR0aW5ncxJRChRlbmFibGVfaW1wZXJzb25hdGlvbhgCIAEoCEIzkkEwMihkZWZhdWx0IGxhbmd1YWdlIGZvciB0aGUgY3VycmVudCBjb250ZXh0SgQiZW4iItwBChZFbWJlZGRlZElmcmFtZVNldHRpbmdzEkcKB2VuYWJsZWQYASABKAhCNpJBMzIxc3RhdGVzIGlmIGlmcmFtZSBlbWJlZGRpbmcgaXMgZW5hYmxlZCBvciBkaXNhYmxlZBJ5Cg9hbGxvd2VkX29yaWdpbnMYAiADKAlCYJJBXTI4b3JpZ2lucyBhbGxvd2VkIGxvYWRpbmcgWklUQURFTCBpbiBhbiBpZnJhbWUgaWYgZW5hYmxlZC5KIVsiZm9vLmJhci5jb20iLCAibG9jYWxob3N0OjgwODAiXULYAQoXY29tLnppdGFkZWwuc2V0dGluZ3MudjJCFVNlY3VyaXR5U2V0dGluZ3NQcm90b1ABWjhnaXRodWIuY29tL3ppdGFkZWwveml0YWRlbC9wa2cvZ3JwYy9zZXR0aW5ncy92MjtzZXR0aW5nc6ICA1pTWKoCE1ppdGFkZWwuU2V0dGluZ3MuVjLKAhNaaXRhZGVsXFNldHRpbmdzXFYy4gIfWml0YWRlbFxTZXR0aW5nc1xWMlxHUEJNZXRhZGF0YeoCFVppdGFkZWw6OlNldHRpbmdzOjpWMmIGcHJvdG8z", [file_protoc_gen_openapiv2_options_annotations]);

/**
 * Describes the message zitadel.settings.v2.SecuritySettings.
 * Use `create(SecuritySettingsSchema)` to create a new message.
 */
export const SecuritySettingsSchema = /*@__PURE__*/
  messageDesc(file_zitadel_settings_v2_security_settings, 0);

/**
 * Describes the message zitadel.settings.v2.EmbeddedIframeSettings.
 * Use `create(EmbeddedIframeSettingsSchema)` to create a new message.
 */
export const EmbeddedIframeSettingsSchema = /*@__PURE__*/
  messageDesc(file_zitadel_settings_v2_security_settings, 1);

