// @generated by protoc-gen-es v2.6.0 with parameter "json_types=true,import_extension=js"
// @generated from file zitadel/settings/v2/settings_service.proto (package zitadel.settings.v2, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import type { JsonObject, Message } from "@bufbuild/protobuf";
import type { Details, DetailsJson, ListDetails, ListDetailsJson, RequestContext, RequestContextJson } from "../../object/v2/object_pb.js";
import type { IdentityProvider, IdentityProviderJson, LoginSettings, LoginSettingsJson } from "./login_settings_pb.js";
import type { PasswordComplexitySettings, PasswordComplexitySettingsJson, PasswordExpirySettings, PasswordExpirySettingsJson } from "./password_settings_pb.js";
import type { BrandingSettings, BrandingSettingsJson } from "./branding_settings_pb.js";
import type { DomainSettings, DomainSettingsJson } from "./domain_settings_pb.js";
import type { LegalAndSupportSettings, LegalAndSupportSettingsJson } from "./legal_settings_pb.js";
import type { LockoutSettings, LockoutSettingsJson } from "./lockout_settings_pb.js";
import type { EmbeddedIframeSettings, EmbeddedIframeSettingsJson, SecuritySettings, SecuritySettingsJson } from "./security_settings_pb.js";
import type { StructJson } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file zitadel/settings/v2/settings_service.proto.
 */
export declare const file_zitadel_settings_v2_settings_service: GenFile;

/**
 * @generated from message zitadel.settings.v2.GetLoginSettingsRequest
 */
export declare type GetLoginSettingsRequest = Message<"zitadel.settings.v2.GetLoginSettingsRequest"> & {
  /**
   * @generated from field: zitadel.object.v2.RequestContext ctx = 1;
   */
  ctx?: RequestContext;
};

/**
 * @generated from message zitadel.settings.v2.GetLoginSettingsRequest
 */
export declare type GetLoginSettingsRequestJson = {
  /**
   * @generated from field: zitadel.object.v2.RequestContext ctx = 1;
   */
  ctx?: RequestContextJson;
};

/**
 * Describes the message zitadel.settings.v2.GetLoginSettingsRequest.
 * Use `create(GetLoginSettingsRequestSchema)` to create a new message.
 */
export declare const GetLoginSettingsRequestSchema: GenMessage<GetLoginSettingsRequest, {jsonType: GetLoginSettingsRequestJson}>;

/**
 * @generated from message zitadel.settings.v2.GetLoginSettingsResponse
 */
export declare type GetLoginSettingsResponse = Message<"zitadel.settings.v2.GetLoginSettingsResponse"> & {
  /**
   * @generated from field: zitadel.object.v2.Details details = 1;
   */
  details?: Details;

  /**
   * @generated from field: zitadel.settings.v2.LoginSettings settings = 2;
   */
  settings?: LoginSettings;
};

/**
 * @generated from message zitadel.settings.v2.GetLoginSettingsResponse
 */
export declare type GetLoginSettingsResponseJson = {
  /**
   * @generated from field: zitadel.object.v2.Details details = 1;
   */
  details?: DetailsJson;

  /**
   * @generated from field: zitadel.settings.v2.LoginSettings settings = 2;
   */
  settings?: LoginSettingsJson;
};

/**
 * Describes the message zitadel.settings.v2.GetLoginSettingsResponse.
 * Use `create(GetLoginSettingsResponseSchema)` to create a new message.
 */
export declare const GetLoginSettingsResponseSchema: GenMessage<GetLoginSettingsResponse, {jsonType: GetLoginSettingsResponseJson}>;

/**
 * @generated from message zitadel.settings.v2.GetPasswordComplexitySettingsRequest
 */
export declare type GetPasswordComplexitySettingsRequest = Message<"zitadel.settings.v2.GetPasswordComplexitySettingsRequest"> & {
  /**
   * @generated from field: zitadel.object.v2.RequestContext ctx = 1;
   */
  ctx?: RequestContext;
};

/**
 * @generated from message zitadel.settings.v2.GetPasswordComplexitySettingsRequest
 */
export declare type GetPasswordComplexitySettingsRequestJson = {
  /**
   * @generated from field: zitadel.object.v2.RequestContext ctx = 1;
   */
  ctx?: RequestContextJson;
};

/**
 * Describes the message zitadel.settings.v2.GetPasswordComplexitySettingsRequest.
 * Use `create(GetPasswordComplexitySettingsRequestSchema)` to create a new message.
 */
export declare const GetPasswordComplexitySettingsRequestSchema: GenMessage<GetPasswordComplexitySettingsRequest, {jsonType: GetPasswordComplexitySettingsRequestJson}>;

/**
 * @generated from message zitadel.settings.v2.GetPasswordComplexitySettingsResponse
 */
export declare type GetPasswordComplexitySettingsResponse = Message<"zitadel.settings.v2.GetPasswordComplexitySettingsResponse"> & {
  /**
   * @generated from field: zitadel.object.v2.Details details = 1;
   */
  details?: Details;

  /**
   * @generated from field: zitadel.settings.v2.PasswordComplexitySettings settings = 2;
   */
  settings?: PasswordComplexitySettings;
};

/**
 * @generated from message zitadel.settings.v2.GetPasswordComplexitySettingsResponse
 */
export declare type GetPasswordComplexitySettingsResponseJson = {
  /**
   * @generated from field: zitadel.object.v2.Details details = 1;
   */
  details?: DetailsJson;

  /**
   * @generated from field: zitadel.settings.v2.PasswordComplexitySettings settings = 2;
   */
  settings?: PasswordComplexitySettingsJson;
};

/**
 * Describes the message zitadel.settings.v2.GetPasswordComplexitySettingsResponse.
 * Use `create(GetPasswordComplexitySettingsResponseSchema)` to create a new message.
 */
export declare const GetPasswordComplexitySettingsResponseSchema: GenMessage<GetPasswordComplexitySettingsResponse, {jsonType: GetPasswordComplexitySettingsResponseJson}>;

/**
 * @generated from message zitadel.settings.v2.GetPasswordExpirySettingsRequest
 */
export declare type GetPasswordExpirySettingsRequest = Message<"zitadel.settings.v2.GetPasswordExpirySettingsRequest"> & {
  /**
   * @generated from field: zitadel.object.v2.RequestContext ctx = 1;
   */
  ctx?: RequestContext;
};

/**
 * @generated from message zitadel.settings.v2.GetPasswordExpirySettingsRequest
 */
export declare type GetPasswordExpirySettingsRequestJson = {
  /**
   * @generated from field: zitadel.object.v2.RequestContext ctx = 1;
   */
  ctx?: RequestContextJson;
};

/**
 * Describes the message zitadel.settings.v2.GetPasswordExpirySettingsRequest.
 * Use `create(GetPasswordExpirySettingsRequestSchema)` to create a new message.
 */
export declare const GetPasswordExpirySettingsRequestSchema: GenMessage<GetPasswordExpirySettingsRequest, {jsonType: GetPasswordExpirySettingsRequestJson}>;

/**
 * @generated from message zitadel.settings.v2.GetPasswordExpirySettingsResponse
 */
export declare type GetPasswordExpirySettingsResponse = Message<"zitadel.settings.v2.GetPasswordExpirySettingsResponse"> & {
  /**
   * @generated from field: zitadel.object.v2.Details details = 1;
   */
  details?: Details;

  /**
   * @generated from field: zitadel.settings.v2.PasswordExpirySettings settings = 2;
   */
  settings?: PasswordExpirySettings;
};

/**
 * @generated from message zitadel.settings.v2.GetPasswordExpirySettingsResponse
 */
export declare type GetPasswordExpirySettingsResponseJson = {
  /**
   * @generated from field: zitadel.object.v2.Details details = 1;
   */
  details?: DetailsJson;

  /**
   * @generated from field: zitadel.settings.v2.PasswordExpirySettings settings = 2;
   */
  settings?: PasswordExpirySettingsJson;
};

/**
 * Describes the message zitadel.settings.v2.GetPasswordExpirySettingsResponse.
 * Use `create(GetPasswordExpirySettingsResponseSchema)` to create a new message.
 */
export declare const GetPasswordExpirySettingsResponseSchema: GenMessage<GetPasswordExpirySettingsResponse, {jsonType: GetPasswordExpirySettingsResponseJson}>;

/**
 * @generated from message zitadel.settings.v2.GetBrandingSettingsRequest
 */
export declare type GetBrandingSettingsRequest = Message<"zitadel.settings.v2.GetBrandingSettingsRequest"> & {
  /**
   * @generated from field: zitadel.object.v2.RequestContext ctx = 1;
   */
  ctx?: RequestContext;
};

/**
 * @generated from message zitadel.settings.v2.GetBrandingSettingsRequest
 */
export declare type GetBrandingSettingsRequestJson = {
  /**
   * @generated from field: zitadel.object.v2.RequestContext ctx = 1;
   */
  ctx?: RequestContextJson;
};

/**
 * Describes the message zitadel.settings.v2.GetBrandingSettingsRequest.
 * Use `create(GetBrandingSettingsRequestSchema)` to create a new message.
 */
export declare const GetBrandingSettingsRequestSchema: GenMessage<GetBrandingSettingsRequest, {jsonType: GetBrandingSettingsRequestJson}>;

/**
 * @generated from message zitadel.settings.v2.GetBrandingSettingsResponse
 */
export declare type GetBrandingSettingsResponse = Message<"zitadel.settings.v2.GetBrandingSettingsResponse"> & {
  /**
   * @generated from field: zitadel.object.v2.Details details = 1;
   */
  details?: Details;

  /**
   * @generated from field: zitadel.settings.v2.BrandingSettings settings = 2;
   */
  settings?: BrandingSettings;
};

/**
 * @generated from message zitadel.settings.v2.GetBrandingSettingsResponse
 */
export declare type GetBrandingSettingsResponseJson = {
  /**
   * @generated from field: zitadel.object.v2.Details details = 1;
   */
  details?: DetailsJson;

  /**
   * @generated from field: zitadel.settings.v2.BrandingSettings settings = 2;
   */
  settings?: BrandingSettingsJson;
};

/**
 * Describes the message zitadel.settings.v2.GetBrandingSettingsResponse.
 * Use `create(GetBrandingSettingsResponseSchema)` to create a new message.
 */
export declare const GetBrandingSettingsResponseSchema: GenMessage<GetBrandingSettingsResponse, {jsonType: GetBrandingSettingsResponseJson}>;

/**
 * @generated from message zitadel.settings.v2.GetDomainSettingsRequest
 */
export declare type GetDomainSettingsRequest = Message<"zitadel.settings.v2.GetDomainSettingsRequest"> & {
  /**
   * @generated from field: zitadel.object.v2.RequestContext ctx = 1;
   */
  ctx?: RequestContext;
};

/**
 * @generated from message zitadel.settings.v2.GetDomainSettingsRequest
 */
export declare type GetDomainSettingsRequestJson = {
  /**
   * @generated from field: zitadel.object.v2.RequestContext ctx = 1;
   */
  ctx?: RequestContextJson;
};

/**
 * Describes the message zitadel.settings.v2.GetDomainSettingsRequest.
 * Use `create(GetDomainSettingsRequestSchema)` to create a new message.
 */
export declare const GetDomainSettingsRequestSchema: GenMessage<GetDomainSettingsRequest, {jsonType: GetDomainSettingsRequestJson}>;

/**
 * @generated from message zitadel.settings.v2.GetDomainSettingsResponse
 */
export declare type GetDomainSettingsResponse = Message<"zitadel.settings.v2.GetDomainSettingsResponse"> & {
  /**
   * @generated from field: zitadel.object.v2.Details details = 1;
   */
  details?: Details;

  /**
   * @generated from field: zitadel.settings.v2.DomainSettings settings = 2;
   */
  settings?: DomainSettings;
};

/**
 * @generated from message zitadel.settings.v2.GetDomainSettingsResponse
 */
export declare type GetDomainSettingsResponseJson = {
  /**
   * @generated from field: zitadel.object.v2.Details details = 1;
   */
  details?: DetailsJson;

  /**
   * @generated from field: zitadel.settings.v2.DomainSettings settings = 2;
   */
  settings?: DomainSettingsJson;
};

/**
 * Describes the message zitadel.settings.v2.GetDomainSettingsResponse.
 * Use `create(GetDomainSettingsResponseSchema)` to create a new message.
 */
export declare const GetDomainSettingsResponseSchema: GenMessage<GetDomainSettingsResponse, {jsonType: GetDomainSettingsResponseJson}>;

/**
 * @generated from message zitadel.settings.v2.GetLegalAndSupportSettingsRequest
 */
export declare type GetLegalAndSupportSettingsRequest = Message<"zitadel.settings.v2.GetLegalAndSupportSettingsRequest"> & {
  /**
   * @generated from field: zitadel.object.v2.RequestContext ctx = 1;
   */
  ctx?: RequestContext;
};

/**
 * @generated from message zitadel.settings.v2.GetLegalAndSupportSettingsRequest
 */
export declare type GetLegalAndSupportSettingsRequestJson = {
  /**
   * @generated from field: zitadel.object.v2.RequestContext ctx = 1;
   */
  ctx?: RequestContextJson;
};

/**
 * Describes the message zitadel.settings.v2.GetLegalAndSupportSettingsRequest.
 * Use `create(GetLegalAndSupportSettingsRequestSchema)` to create a new message.
 */
export declare const GetLegalAndSupportSettingsRequestSchema: GenMessage<GetLegalAndSupportSettingsRequest, {jsonType: GetLegalAndSupportSettingsRequestJson}>;

/**
 * @generated from message zitadel.settings.v2.GetLegalAndSupportSettingsResponse
 */
export declare type GetLegalAndSupportSettingsResponse = Message<"zitadel.settings.v2.GetLegalAndSupportSettingsResponse"> & {
  /**
   * @generated from field: zitadel.object.v2.Details details = 1;
   */
  details?: Details;

  /**
   * @generated from field: zitadel.settings.v2.LegalAndSupportSettings settings = 2;
   */
  settings?: LegalAndSupportSettings;
};

/**
 * @generated from message zitadel.settings.v2.GetLegalAndSupportSettingsResponse
 */
export declare type GetLegalAndSupportSettingsResponseJson = {
  /**
   * @generated from field: zitadel.object.v2.Details details = 1;
   */
  details?: DetailsJson;

  /**
   * @generated from field: zitadel.settings.v2.LegalAndSupportSettings settings = 2;
   */
  settings?: LegalAndSupportSettingsJson;
};

/**
 * Describes the message zitadel.settings.v2.GetLegalAndSupportSettingsResponse.
 * Use `create(GetLegalAndSupportSettingsResponseSchema)` to create a new message.
 */
export declare const GetLegalAndSupportSettingsResponseSchema: GenMessage<GetLegalAndSupportSettingsResponse, {jsonType: GetLegalAndSupportSettingsResponseJson}>;

/**
 * @generated from message zitadel.settings.v2.GetLockoutSettingsRequest
 */
export declare type GetLockoutSettingsRequest = Message<"zitadel.settings.v2.GetLockoutSettingsRequest"> & {
  /**
   * @generated from field: zitadel.object.v2.RequestContext ctx = 1;
   */
  ctx?: RequestContext;
};

/**
 * @generated from message zitadel.settings.v2.GetLockoutSettingsRequest
 */
export declare type GetLockoutSettingsRequestJson = {
  /**
   * @generated from field: zitadel.object.v2.RequestContext ctx = 1;
   */
  ctx?: RequestContextJson;
};

/**
 * Describes the message zitadel.settings.v2.GetLockoutSettingsRequest.
 * Use `create(GetLockoutSettingsRequestSchema)` to create a new message.
 */
export declare const GetLockoutSettingsRequestSchema: GenMessage<GetLockoutSettingsRequest, {jsonType: GetLockoutSettingsRequestJson}>;

/**
 * @generated from message zitadel.settings.v2.GetLockoutSettingsResponse
 */
export declare type GetLockoutSettingsResponse = Message<"zitadel.settings.v2.GetLockoutSettingsResponse"> & {
  /**
   * @generated from field: zitadel.object.v2.Details details = 1;
   */
  details?: Details;

  /**
   * @generated from field: zitadel.settings.v2.LockoutSettings settings = 2;
   */
  settings?: LockoutSettings;
};

/**
 * @generated from message zitadel.settings.v2.GetLockoutSettingsResponse
 */
export declare type GetLockoutSettingsResponseJson = {
  /**
   * @generated from field: zitadel.object.v2.Details details = 1;
   */
  details?: DetailsJson;

  /**
   * @generated from field: zitadel.settings.v2.LockoutSettings settings = 2;
   */
  settings?: LockoutSettingsJson;
};

/**
 * Describes the message zitadel.settings.v2.GetLockoutSettingsResponse.
 * Use `create(GetLockoutSettingsResponseSchema)` to create a new message.
 */
export declare const GetLockoutSettingsResponseSchema: GenMessage<GetLockoutSettingsResponse, {jsonType: GetLockoutSettingsResponseJson}>;

/**
 * @generated from message zitadel.settings.v2.GetActiveIdentityProvidersRequest
 */
export declare type GetActiveIdentityProvidersRequest = Message<"zitadel.settings.v2.GetActiveIdentityProvidersRequest"> & {
  /**
   * @generated from field: zitadel.object.v2.RequestContext ctx = 1;
   */
  ctx?: RequestContext;

  /**
   * @generated from field: optional bool creation_allowed = 2;
   */
  creationAllowed?: boolean;

  /**
   * @generated from field: optional bool linking_allowed = 3;
   */
  linkingAllowed?: boolean;

  /**
   * @generated from field: optional bool auto_creation = 4;
   */
  autoCreation?: boolean;

  /**
   * @generated from field: optional bool auto_linking = 5;
   */
  autoLinking?: boolean;
};

/**
 * @generated from message zitadel.settings.v2.GetActiveIdentityProvidersRequest
 */
export declare type GetActiveIdentityProvidersRequestJson = {
  /**
   * @generated from field: zitadel.object.v2.RequestContext ctx = 1;
   */
  ctx?: RequestContextJson;

  /**
   * @generated from field: optional bool creation_allowed = 2;
   */
  creationAllowed?: boolean;

  /**
   * @generated from field: optional bool linking_allowed = 3;
   */
  linkingAllowed?: boolean;

  /**
   * @generated from field: optional bool auto_creation = 4;
   */
  autoCreation?: boolean;

  /**
   * @generated from field: optional bool auto_linking = 5;
   */
  autoLinking?: boolean;
};

/**
 * Describes the message zitadel.settings.v2.GetActiveIdentityProvidersRequest.
 * Use `create(GetActiveIdentityProvidersRequestSchema)` to create a new message.
 */
export declare const GetActiveIdentityProvidersRequestSchema: GenMessage<GetActiveIdentityProvidersRequest, {jsonType: GetActiveIdentityProvidersRequestJson}>;

/**
 * @generated from message zitadel.settings.v2.GetActiveIdentityProvidersResponse
 */
export declare type GetActiveIdentityProvidersResponse = Message<"zitadel.settings.v2.GetActiveIdentityProvidersResponse"> & {
  /**
   * @generated from field: zitadel.object.v2.ListDetails details = 1;
   */
  details?: ListDetails;

  /**
   * @generated from field: repeated zitadel.settings.v2.IdentityProvider identity_providers = 2;
   */
  identityProviders: IdentityProvider[];
};

/**
 * @generated from message zitadel.settings.v2.GetActiveIdentityProvidersResponse
 */
export declare type GetActiveIdentityProvidersResponseJson = {
  /**
   * @generated from field: zitadel.object.v2.ListDetails details = 1;
   */
  details?: ListDetailsJson;

  /**
   * @generated from field: repeated zitadel.settings.v2.IdentityProvider identity_providers = 2;
   */
  identityProviders?: IdentityProviderJson[];
};

/**
 * Describes the message zitadel.settings.v2.GetActiveIdentityProvidersResponse.
 * Use `create(GetActiveIdentityProvidersResponseSchema)` to create a new message.
 */
export declare const GetActiveIdentityProvidersResponseSchema: GenMessage<GetActiveIdentityProvidersResponse, {jsonType: GetActiveIdentityProvidersResponseJson}>;

/**
 * @generated from message zitadel.settings.v2.GetGeneralSettingsRequest
 */
export declare type GetGeneralSettingsRequest = Message<"zitadel.settings.v2.GetGeneralSettingsRequest"> & {
};

/**
 * @generated from message zitadel.settings.v2.GetGeneralSettingsRequest
 */
export declare type GetGeneralSettingsRequestJson = {
};

/**
 * Describes the message zitadel.settings.v2.GetGeneralSettingsRequest.
 * Use `create(GetGeneralSettingsRequestSchema)` to create a new message.
 */
export declare const GetGeneralSettingsRequestSchema: GenMessage<GetGeneralSettingsRequest, {jsonType: GetGeneralSettingsRequestJson}>;

/**
 * @generated from message zitadel.settings.v2.GetGeneralSettingsResponse
 */
export declare type GetGeneralSettingsResponse = Message<"zitadel.settings.v2.GetGeneralSettingsResponse"> & {
  /**
   * @generated from field: string default_org_id = 1;
   */
  defaultOrgId: string;

  /**
   * @generated from field: string default_language = 2;
   */
  defaultLanguage: string;

  /**
   * @generated from field: repeated string supported_languages = 3;
   */
  supportedLanguages: string[];
};

/**
 * @generated from message zitadel.settings.v2.GetGeneralSettingsResponse
 */
export declare type GetGeneralSettingsResponseJson = {
  /**
   * @generated from field: string default_org_id = 1;
   */
  defaultOrgId?: string;

  /**
   * @generated from field: string default_language = 2;
   */
  defaultLanguage?: string;

  /**
   * @generated from field: repeated string supported_languages = 3;
   */
  supportedLanguages?: string[];
};

/**
 * Describes the message zitadel.settings.v2.GetGeneralSettingsResponse.
 * Use `create(GetGeneralSettingsResponseSchema)` to create a new message.
 */
export declare const GetGeneralSettingsResponseSchema: GenMessage<GetGeneralSettingsResponse, {jsonType: GetGeneralSettingsResponseJson}>;

/**
 * This is an empty request
 *
 * @generated from message zitadel.settings.v2.GetSecuritySettingsRequest
 */
export declare type GetSecuritySettingsRequest = Message<"zitadel.settings.v2.GetSecuritySettingsRequest"> & {
};

/**
 * This is an empty request
 *
 * @generated from message zitadel.settings.v2.GetSecuritySettingsRequest
 */
export declare type GetSecuritySettingsRequestJson = {
};

/**
 * Describes the message zitadel.settings.v2.GetSecuritySettingsRequest.
 * Use `create(GetSecuritySettingsRequestSchema)` to create a new message.
 */
export declare const GetSecuritySettingsRequestSchema: GenMessage<GetSecuritySettingsRequest, {jsonType: GetSecuritySettingsRequestJson}>;

/**
 * @generated from message zitadel.settings.v2.GetSecuritySettingsResponse
 */
export declare type GetSecuritySettingsResponse = Message<"zitadel.settings.v2.GetSecuritySettingsResponse"> & {
  /**
   * @generated from field: zitadel.object.v2.Details details = 1;
   */
  details?: Details;

  /**
   * @generated from field: zitadel.settings.v2.SecuritySettings settings = 2;
   */
  settings?: SecuritySettings;
};

/**
 * @generated from message zitadel.settings.v2.GetSecuritySettingsResponse
 */
export declare type GetSecuritySettingsResponseJson = {
  /**
   * @generated from field: zitadel.object.v2.Details details = 1;
   */
  details?: DetailsJson;

  /**
   * @generated from field: zitadel.settings.v2.SecuritySettings settings = 2;
   */
  settings?: SecuritySettingsJson;
};

/**
 * Describes the message zitadel.settings.v2.GetSecuritySettingsResponse.
 * Use `create(GetSecuritySettingsResponseSchema)` to create a new message.
 */
export declare const GetSecuritySettingsResponseSchema: GenMessage<GetSecuritySettingsResponse, {jsonType: GetSecuritySettingsResponseJson}>;

/**
 * @generated from message zitadel.settings.v2.SetSecuritySettingsRequest
 */
export declare type SetSecuritySettingsRequest = Message<"zitadel.settings.v2.SetSecuritySettingsRequest"> & {
  /**
   * @generated from field: zitadel.settings.v2.EmbeddedIframeSettings embedded_iframe = 1;
   */
  embeddedIframe?: EmbeddedIframeSettings;

  /**
   * @generated from field: bool enable_impersonation = 2;
   */
  enableImpersonation: boolean;
};

/**
 * @generated from message zitadel.settings.v2.SetSecuritySettingsRequest
 */
export declare type SetSecuritySettingsRequestJson = {
  /**
   * @generated from field: zitadel.settings.v2.EmbeddedIframeSettings embedded_iframe = 1;
   */
  embeddedIframe?: EmbeddedIframeSettingsJson;

  /**
   * @generated from field: bool enable_impersonation = 2;
   */
  enableImpersonation?: boolean;
};

/**
 * Describes the message zitadel.settings.v2.SetSecuritySettingsRequest.
 * Use `create(SetSecuritySettingsRequestSchema)` to create a new message.
 */
export declare const SetSecuritySettingsRequestSchema: GenMessage<SetSecuritySettingsRequest, {jsonType: SetSecuritySettingsRequestJson}>;

/**
 * @generated from message zitadel.settings.v2.SetSecuritySettingsResponse
 */
export declare type SetSecuritySettingsResponse = Message<"zitadel.settings.v2.SetSecuritySettingsResponse"> & {
  /**
   * @generated from field: zitadel.object.v2.Details details = 1;
   */
  details?: Details;
};

/**
 * @generated from message zitadel.settings.v2.SetSecuritySettingsResponse
 */
export declare type SetSecuritySettingsResponseJson = {
  /**
   * @generated from field: zitadel.object.v2.Details details = 1;
   */
  details?: DetailsJson;
};

/**
 * Describes the message zitadel.settings.v2.SetSecuritySettingsResponse.
 * Use `create(SetSecuritySettingsResponseSchema)` to create a new message.
 */
export declare const SetSecuritySettingsResponseSchema: GenMessage<SetSecuritySettingsResponse, {jsonType: SetSecuritySettingsResponseJson}>;

/**
 * @generated from message zitadel.settings.v2.GetHostedLoginTranslationRequest
 */
export declare type GetHostedLoginTranslationRequest = Message<"zitadel.settings.v2.GetHostedLoginTranslationRequest"> & {
  /**
   * @generated from oneof zitadel.settings.v2.GetHostedLoginTranslationRequest.level
   */
  level: {
    /**
     * @generated from field: bool system = 1;
     */
    value: boolean;
    case: "system";
  } | {
    /**
     * @generated from field: bool instance = 2;
     */
    value: boolean;
    case: "instance";
  } | {
    /**
     * @generated from field: string organization_id = 3;
     */
    value: string;
    case: "organizationId";
  } | { case: undefined; value?: undefined };

  /**
   * @generated from field: string locale = 4;
   */
  locale: string;

  /**
   * if set to true, higher levels are ignored, if false higher levels are merged into the file
   *
   * @generated from field: bool ignore_inheritance = 5;
   */
  ignoreInheritance: boolean;
};

/**
 * @generated from message zitadel.settings.v2.GetHostedLoginTranslationRequest
 */
export declare type GetHostedLoginTranslationRequestJson = {
  /**
   * @generated from field: bool system = 1;
   */
  system?: boolean;

  /**
   * @generated from field: bool instance = 2;
   */
  instance?: boolean;

  /**
   * @generated from field: string organization_id = 3;
   */
  organizationId?: string;

  /**
   * @generated from field: string locale = 4;
   */
  locale?: string;

  /**
   * if set to true, higher levels are ignored, if false higher levels are merged into the file
   *
   * @generated from field: bool ignore_inheritance = 5;
   */
  ignoreInheritance?: boolean;
};

/**
 * Describes the message zitadel.settings.v2.GetHostedLoginTranslationRequest.
 * Use `create(GetHostedLoginTranslationRequestSchema)` to create a new message.
 */
export declare const GetHostedLoginTranslationRequestSchema: GenMessage<GetHostedLoginTranslationRequest, {jsonType: GetHostedLoginTranslationRequestJson}>;

/**
 * @generated from message zitadel.settings.v2.GetHostedLoginTranslationResponse
 */
export declare type GetHostedLoginTranslationResponse = Message<"zitadel.settings.v2.GetHostedLoginTranslationResponse"> & {
  /**
   * hash of the payload
   *
   * @generated from field: string etag = 1;
   */
  etag: string;

  /**
   * @generated from field: google.protobuf.Struct translations = 2;
   */
  translations?: JsonObject;
};

/**
 * @generated from message zitadel.settings.v2.GetHostedLoginTranslationResponse
 */
export declare type GetHostedLoginTranslationResponseJson = {
  /**
   * hash of the payload
   *
   * @generated from field: string etag = 1;
   */
  etag?: string;

  /**
   * @generated from field: google.protobuf.Struct translations = 2;
   */
  translations?: StructJson;
};

/**
 * Describes the message zitadel.settings.v2.GetHostedLoginTranslationResponse.
 * Use `create(GetHostedLoginTranslationResponseSchema)` to create a new message.
 */
export declare const GetHostedLoginTranslationResponseSchema: GenMessage<GetHostedLoginTranslationResponse, {jsonType: GetHostedLoginTranslationResponseJson}>;

/**
 * @generated from message zitadel.settings.v2.SetHostedLoginTranslationRequest
 */
export declare type SetHostedLoginTranslationRequest = Message<"zitadel.settings.v2.SetHostedLoginTranslationRequest"> & {
  /**
   * @generated from oneof zitadel.settings.v2.SetHostedLoginTranslationRequest.level
   */
  level: {
    /**
     * @generated from field: bool instance = 1;
     */
    value: boolean;
    case: "instance";
  } | {
    /**
     * @generated from field: string organization_id = 2;
     */
    value: string;
    case: "organizationId";
  } | { case: undefined; value?: undefined };

  /**
   * @generated from field: string locale = 3;
   */
  locale: string;

  /**
   * @generated from field: google.protobuf.Struct translations = 4;
   */
  translations?: JsonObject;
};

/**
 * @generated from message zitadel.settings.v2.SetHostedLoginTranslationRequest
 */
export declare type SetHostedLoginTranslationRequestJson = {
  /**
   * @generated from field: bool instance = 1;
   */
  instance?: boolean;

  /**
   * @generated from field: string organization_id = 2;
   */
  organizationId?: string;

  /**
   * @generated from field: string locale = 3;
   */
  locale?: string;

  /**
   * @generated from field: google.protobuf.Struct translations = 4;
   */
  translations?: StructJson;
};

/**
 * Describes the message zitadel.settings.v2.SetHostedLoginTranslationRequest.
 * Use `create(SetHostedLoginTranslationRequestSchema)` to create a new message.
 */
export declare const SetHostedLoginTranslationRequestSchema: GenMessage<SetHostedLoginTranslationRequest, {jsonType: SetHostedLoginTranslationRequestJson}>;

/**
 * @generated from message zitadel.settings.v2.SetHostedLoginTranslationResponse
 */
export declare type SetHostedLoginTranslationResponse = Message<"zitadel.settings.v2.SetHostedLoginTranslationResponse"> & {
  /**
   * hash of the saved translation. Valid only when ignore_inheritance = true
   *
   * @generated from field: string etag = 1;
   */
  etag: string;
};

/**
 * @generated from message zitadel.settings.v2.SetHostedLoginTranslationResponse
 */
export declare type SetHostedLoginTranslationResponseJson = {
  /**
   * hash of the saved translation. Valid only when ignore_inheritance = true
   *
   * @generated from field: string etag = 1;
   */
  etag?: string;
};

/**
 * Describes the message zitadel.settings.v2.SetHostedLoginTranslationResponse.
 * Use `create(SetHostedLoginTranslationResponseSchema)` to create a new message.
 */
export declare const SetHostedLoginTranslationResponseSchema: GenMessage<SetHostedLoginTranslationResponse, {jsonType: SetHostedLoginTranslationResponseJson}>;

/**
 * @generated from service zitadel.settings.v2.SettingsService
 */
export declare const SettingsService: GenService<{
  /**
   * Get basic information over the instance
   *
   * @generated from rpc zitadel.settings.v2.SettingsService.GetGeneralSettings
   */
  getGeneralSettings: {
    methodKind: "unary";
    input: typeof GetGeneralSettingsRequestSchema;
    output: typeof GetGeneralSettingsResponseSchema;
  },
  /**
   * Get the login settings
   *
   * @generated from rpc zitadel.settings.v2.SettingsService.GetLoginSettings
   */
  getLoginSettings: {
    methodKind: "unary";
    input: typeof GetLoginSettingsRequestSchema;
    output: typeof GetLoginSettingsResponseSchema;
  },
  /**
   * Get the current active identity providers
   *
   * @generated from rpc zitadel.settings.v2.SettingsService.GetActiveIdentityProviders
   */
  getActiveIdentityProviders: {
    methodKind: "unary";
    input: typeof GetActiveIdentityProvidersRequestSchema;
    output: typeof GetActiveIdentityProvidersResponseSchema;
  },
  /**
   * Get the password complexity settings
   *
   * @generated from rpc zitadel.settings.v2.SettingsService.GetPasswordComplexitySettings
   */
  getPasswordComplexitySettings: {
    methodKind: "unary";
    input: typeof GetPasswordComplexitySettingsRequestSchema;
    output: typeof GetPasswordComplexitySettingsResponseSchema;
  },
  /**
   * Get the password expiry settings
   *
   * @generated from rpc zitadel.settings.v2.SettingsService.GetPasswordExpirySettings
   */
  getPasswordExpirySettings: {
    methodKind: "unary";
    input: typeof GetPasswordExpirySettingsRequestSchema;
    output: typeof GetPasswordExpirySettingsResponseSchema;
  },
  /**
   * Get the current active branding settings
   *
   * @generated from rpc zitadel.settings.v2.SettingsService.GetBrandingSettings
   */
  getBrandingSettings: {
    methodKind: "unary";
    input: typeof GetBrandingSettingsRequestSchema;
    output: typeof GetBrandingSettingsResponseSchema;
  },
  /**
   * Get the domain settings
   *
   * @generated from rpc zitadel.settings.v2.SettingsService.GetDomainSettings
   */
  getDomainSettings: {
    methodKind: "unary";
    input: typeof GetDomainSettingsRequestSchema;
    output: typeof GetDomainSettingsResponseSchema;
  },
  /**
   * Get the legal and support settings
   *
   * @generated from rpc zitadel.settings.v2.SettingsService.GetLegalAndSupportSettings
   */
  getLegalAndSupportSettings: {
    methodKind: "unary";
    input: typeof GetLegalAndSupportSettingsRequestSchema;
    output: typeof GetLegalAndSupportSettingsResponseSchema;
  },
  /**
   * Get the lockout settings
   *
   * @generated from rpc zitadel.settings.v2.SettingsService.GetLockoutSettings
   */
  getLockoutSettings: {
    methodKind: "unary";
    input: typeof GetLockoutSettingsRequestSchema;
    output: typeof GetLockoutSettingsResponseSchema;
  },
  /**
   * Get the security settings
   *
   * @generated from rpc zitadel.settings.v2.SettingsService.GetSecuritySettings
   */
  getSecuritySettings: {
    methodKind: "unary";
    input: typeof GetSecuritySettingsRequestSchema;
    output: typeof GetSecuritySettingsResponseSchema;
  },
  /**
   * Set the security settings
   *
   * @generated from rpc zitadel.settings.v2.SettingsService.SetSecuritySettings
   */
  setSecuritySettings: {
    methodKind: "unary";
    input: typeof SetSecuritySettingsRequestSchema;
    output: typeof SetSecuritySettingsResponseSchema;
  },
  /**
   * Get Hosted Login Translation
   *
   * Returns the translations in the requested locale for the hosted login.
   * The translations returned are based on the input level specified (system, instance or organization).
   *
   * If the requested level doesn't contain all translations, and ignore_inheritance is set to false,
   * a merging process fallbacks onto the higher levels ensuring all keys in the file have a translation,
   * which could be in the default language if the one of the locale is missing on all levels.
   *
   * The etag returned in the response represents the hash of the translations as they are stored on DB
   * and its reliable only if ignore_inheritance = true.
   *
   * Required permissions:
   *   - `iam.policy.read`
   *
   * @generated from rpc zitadel.settings.v2.SettingsService.GetHostedLoginTranslation
   */
  getHostedLoginTranslation: {
    methodKind: "unary";
    input: typeof GetHostedLoginTranslationRequestSchema;
    output: typeof GetHostedLoginTranslationResponseSchema;
  },
  /**
   * Set Hosted Login Translation
   *
   * Sets the input translations at the specified level (instance or organization) for the input language.
   *
   * Required permissions:
   *   - `iam.policy.write`
   *
   * @generated from rpc zitadel.settings.v2.SettingsService.SetHostedLoginTranslation
   */
  setHostedLoginTranslation: {
    methodKind: "unary";
    input: typeof SetHostedLoginTranslationRequestSchema;
    output: typeof SetHostedLoginTranslationResponseSchema;
  },
}>;

