// @generated by protoc-gen-es v2.6.0 with parameter "json_types=true,import_extension=js"
// @generated from file zitadel/saml/v2/authorization.proto (package zitadel.saml.v2, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, tsEnum } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_duration, file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import { file_protoc_gen_openapiv2_options_annotations } from "../../../protoc-gen-openapiv2/options/annotations_pb.js";

/**
 * Describes the file zitadel/saml/v2/authorization.proto.
 */
export const file_zitadel_saml_v2_authorization = /*@__PURE__*/
  fileDesc("CiN6aXRhZGVsL3NhbWwvdjIvYXV0aG9yaXphdGlvbi5wcm90bxIPeml0YWRlbC5zYW1sLnYyIoAFCgtTQU1MUmVxdWVzdBImCgJpZBgBIAEoCUIakkEXMhVJRCBvZiB0aGUgU0FNTFJlcXVlc3QSXQoNY3JlYXRpb25fZGF0ZRgCIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXBCKpJBJzIlVGltZSB3aGVuIHRoZSBTQU1MUmVxdWVzdCB3YXMgY3JlYXRlZBJSCgZpc3N1ZXIYAyABKAlCQpJBPzI9U0FNTCBlbnRpdHlJRCBvZiB0aGUgYXBwbGljYXRpb24gdGhhdCBjcmVhdGVkIHRoZSBTQU1MUmVxdWVzdBJzChphc3NlcnRpb25fY29uc3VtZXJfc2VydmljZRgEIAEoCUJPkkFMMkpVUkwgd2hpY2ggcG9pbnRzIGJhY2sgdG8gdGhlIGFzc2VydGlvbiBjb25zdW1lciBzZXJ2aWNlIG9mIHRoZSBhcHBsaWNhdGlvbhJQCgtyZWxheV9zdGF0ZRgFIAEoCUI7kkE4MjZSZWxheVN0YXRlIHByb3ZpZGVkIGJ5IHRoZSBhcHBsaWNhdGlvbiBmb3IgdGhlIHJlcXVlc3QSRQoHYmluZGluZxgGIAEoCUI0kkExMi9CaW5kaW5nIHVzZWQgYnkgdGhlIGFwcGxpY2F0aW9uIGZvciB0aGUgcmVxdWVzdDqHAZJBgwEqgAEKKkZpbmQgb3V0IG1vcmUgYWJvdXQgU0FNTFJlcXVlc3QgcGFyYW1ldGVycxJSaHR0cHM6Ly9kb2NzLm9hc2lzLW9wZW4ub3JnL3NlY3VyaXR5L3NhbWwvUG9zdDIuMC9zc3RjLXNhbWwtdGVjaC1vdmVydmlldy0yLjAuaHRtbCJ3ChJBdXRob3JpemF0aW9uRXJyb3ISKwoFZXJyb3IYASABKA4yHC56aXRhZGVsLnNhbWwudjIuRXJyb3JSZWFzb24SHgoRZXJyb3JfZGVzY3JpcHRpb24YAiABKAlIAIgBAUIUChJfZXJyb3JfZGVzY3JpcHRpb24qsQIKC0Vycm9yUmVhc29uEhwKGEVSUk9SX1JFQVNPTl9VTlNQRUNJRklFRBAAEiIKHkVSUk9SX1JFQVNPTl9WRVJTSU9OX01JU1NNQVRDSBABEh4KGkVSUk9SX1JFQVNPTl9BVVRIX05fRkFJTEVEEAISKwonRVJST1JfUkVBU09OX0lOVkFMSURfQVRUUl9OQU1FX09SX1ZBTFVFEAMSJgoiRVJST1JfUkVBU09OX0lOVkFMSURfTkFNRUlEX1BPTElDWRAEEh8KG0VSUk9SX1JFQVNPTl9SRVFVRVNUX0RFTklFRBAFEiQKIEVSUk9SX1JFQVNPTl9SRVFVRVNUX1VOU1VQUE9SVEVEEAYSJAogRVJST1JfUkVBU09OX1VOU1VQUE9SVEVEX0JJTkRJTkcQB0K5AQoTY29tLnppdGFkZWwuc2FtbC52MkISQXV0aG9yaXphdGlvblByb3RvUAFaMGdpdGh1Yi5jb20veml0YWRlbC96aXRhZGVsL3BrZy9ncnBjL3NhbWwvdjI7c2FtbKICA1pTWKoCD1ppdGFkZWwuU2FtbC5WMsoCD1ppdGFkZWxcU2FtbFxWMuICG1ppdGFkZWxcU2FtbFxWMlxHUEJNZXRhZGF0YeoCEVppdGFkZWw6OlNhbWw6OlYyYgZwcm90bzM", [file_google_protobuf_duration, file_google_protobuf_timestamp, file_protoc_gen_openapiv2_options_annotations]);

/**
 * Describes the message zitadel.saml.v2.SAMLRequest.
 * Use `create(SAMLRequestSchema)` to create a new message.
 */
export const SAMLRequestSchema = /*@__PURE__*/
  messageDesc(file_zitadel_saml_v2_authorization, 0);

/**
 * Describes the message zitadel.saml.v2.AuthorizationError.
 * Use `create(AuthorizationErrorSchema)` to create a new message.
 */
export const AuthorizationErrorSchema = /*@__PURE__*/
  messageDesc(file_zitadel_saml_v2_authorization, 1);

/**
 * Describes the enum zitadel.saml.v2.ErrorReason.
 */
export const ErrorReasonSchema = /*@__PURE__*/
  enumDesc(file_zitadel_saml_v2_authorization, 0);

/**
 * @generated from enum zitadel.saml.v2.ErrorReason
 */
export const ErrorReason = /*@__PURE__*/
  tsEnum(ErrorReasonSchema);

