// @generated by protoc-gen-es v2.6.0 with parameter "json_types=true,import_extension=js"
// @generated from file zitadel/saml/v2/authorization.proto (package zitadel.saml.v2, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";
import type { Timestamp, TimestampJson } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file zitadel/saml/v2/authorization.proto.
 */
export declare const file_zitadel_saml_v2_authorization: GenFile;

/**
 * @generated from message zitadel.saml.v2.SAMLRequest
 */
export declare type SAMLRequest = Message<"zitadel.saml.v2.SAMLRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: google.protobuf.Timestamp creation_date = 2;
   */
  creationDate?: Timestamp;

  /**
   * @generated from field: string issuer = 3;
   */
  issuer: string;

  /**
   * @generated from field: string assertion_consumer_service = 4;
   */
  assertionConsumerService: string;

  /**
   * @generated from field: string relay_state = 5;
   */
  relayState: string;

  /**
   * @generated from field: string binding = 6;
   */
  binding: string;
};

/**
 * @generated from message zitadel.saml.v2.SAMLRequest
 */
export declare type SAMLRequestJson = {
  /**
   * @generated from field: string id = 1;
   */
  id?: string;

  /**
   * @generated from field: google.protobuf.Timestamp creation_date = 2;
   */
  creationDate?: TimestampJson;

  /**
   * @generated from field: string issuer = 3;
   */
  issuer?: string;

  /**
   * @generated from field: string assertion_consumer_service = 4;
   */
  assertionConsumerService?: string;

  /**
   * @generated from field: string relay_state = 5;
   */
  relayState?: string;

  /**
   * @generated from field: string binding = 6;
   */
  binding?: string;
};

/**
 * Describes the message zitadel.saml.v2.SAMLRequest.
 * Use `create(SAMLRequestSchema)` to create a new message.
 */
export declare const SAMLRequestSchema: GenMessage<SAMLRequest, {jsonType: SAMLRequestJson}>;

/**
 * @generated from message zitadel.saml.v2.AuthorizationError
 */
export declare type AuthorizationError = Message<"zitadel.saml.v2.AuthorizationError"> & {
  /**
   * @generated from field: zitadel.saml.v2.ErrorReason error = 1;
   */
  error: ErrorReason;

  /**
   * @generated from field: optional string error_description = 2;
   */
  errorDescription?: string;
};

/**
 * @generated from message zitadel.saml.v2.AuthorizationError
 */
export declare type AuthorizationErrorJson = {
  /**
   * @generated from field: zitadel.saml.v2.ErrorReason error = 1;
   */
  error?: ErrorReasonJson;

  /**
   * @generated from field: optional string error_description = 2;
   */
  errorDescription?: string;
};

/**
 * Describes the message zitadel.saml.v2.AuthorizationError.
 * Use `create(AuthorizationErrorSchema)` to create a new message.
 */
export declare const AuthorizationErrorSchema: GenMessage<AuthorizationError, {jsonType: AuthorizationErrorJson}>;

/**
 * @generated from enum zitadel.saml.v2.ErrorReason
 */
export enum ErrorReason {
  /**
   * @generated from enum value: ERROR_REASON_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: ERROR_REASON_VERSION_MISSMATCH = 1;
   */
  VERSION_MISSMATCH = 1,

  /**
   * @generated from enum value: ERROR_REASON_AUTH_N_FAILED = 2;
   */
  AUTH_N_FAILED = 2,

  /**
   * @generated from enum value: ERROR_REASON_INVALID_ATTR_NAME_OR_VALUE = 3;
   */
  INVALID_ATTR_NAME_OR_VALUE = 3,

  /**
   * @generated from enum value: ERROR_REASON_INVALID_NAMEID_POLICY = 4;
   */
  INVALID_NAMEID_POLICY = 4,

  /**
   * @generated from enum value: ERROR_REASON_REQUEST_DENIED = 5;
   */
  REQUEST_DENIED = 5,

  /**
   * @generated from enum value: ERROR_REASON_REQUEST_UNSUPPORTED = 6;
   */
  REQUEST_UNSUPPORTED = 6,

  /**
   * @generated from enum value: ERROR_REASON_UNSUPPORTED_BINDING = 7;
   */
  UNSUPPORTED_BINDING = 7,
}

/**
 * @generated from enum zitadel.saml.v2.ErrorReason
 */
export declare type ErrorReasonJson = "ERROR_REASON_UNSPECIFIED" | "ERROR_REASON_VERSION_MISSMATCH" | "ERROR_REASON_AUTH_N_FAILED" | "ERROR_REASON_INVALID_ATTR_NAME_OR_VALUE" | "ERROR_REASON_INVALID_NAMEID_POLICY" | "ERROR_REASON_REQUEST_DENIED" | "ERROR_REASON_REQUEST_UNSUPPORTED" | "ERROR_REASON_UNSUPPORTED_BINDING";

/**
 * Describes the enum zitadel.saml.v2.ErrorReason.
 */
export declare const ErrorReasonSchema: GenEnum<ErrorReason, ErrorReasonJson>;

